const ROLES = [
    'killer',
    'survivor'
];

const SURVIVORS = [
    'dwight',
    'meg',
    'claudette',
    'jake',
    'nea',
    'laurie',
    'ace',
    'bill',
    'feng',
    'david',
    'quentin',
    'tapp',
    'kate',
    'adam',
    'jeff',
    'jane',
    'ash',
    'nancy',
    'steve',
    'yui',
    'zarina',
    'cheryl',
    'felix',
    'elodie',
    'yun',
    'jill',
    'leon',
    'mikaela',
    'jonah',
    'yoichi',
    'haddie',
    'ada',
    'rebecca',
    'vittorio',
    'thalita',
    'renato',
    'gabriel',
    'nicolas',
    'ellen',
    'alan',
    'sable'
]; // list of all available survivors

const KILLERS = [
    'trapper',
    'wraith',
    'hillbilly',
    'nurse',
    'shape',
    'hag',
    'doctor',
    'huntress',
    'cannibal',
    'nightmare',
    'pig',
    'clown',
    'spirit',
    'legion',
    'plage',
    'ghostface',
    'demogorgon',
    'oni',
    'deathslinger',
    'executioner',
    'blight',
    'twins',
    'trickster',
    'nemesis',
    'cenobite',
    'artist',
    'onryo',
    'dredge',
    'mastermind',
    'knight',
    'skullmerchant',
    'singularity',
    'xenomorph',
    'goodguy',
    'unknown'
]; // list of all available killers

const KILLER_PERKS = [
    'aNursesCalling',
    'agitation',
    'alienInstinct',
    'awakenedAwareness',
    'bamboozle',
    'barbecueAndChilli',
    'batteriesIncluded',
    'beastOfPrey',
    'bitterMurmur',
    'bloodEcho',
    'bloodWarden',
    'bloodhound',
    'brutalStrength',
    'callOfBrine',
    'corruptIntervention',
    'coulrophobia',
    'coupDeGr%3Fce',
    'cruelLimits',
    'darkDevotion',
    'darknessRevealed',
    'deadMansSwitch',
    'deadlock',
    'deathbound',
    'deerstalker',
    'discordance',
    'dissolution',
    'distressing',
    'dragonsGrip',
    'dyingLight',
    'enduring',
    'eruption',
    'fireUp',
    'forcedHesitation',
    'forcedPenance',
    'franklinsDemise',
    'friendsTilTheEnd',
    'furtiveChase',
    'gameAfoot',
    'gearhead',
    'geneticLimits',
    'grimEmbrace',
    'hexBloodFavour',
    'hexCrowdControl',
    'hexDevourHope',
    'hexFaceTheDarkness',
    'hexHauntedGround',
    'hexHuntressLullaby',
    'hexNoOneEscapesDeath',
    'hexPentimento',
    'hexPlaything',
    'hexRetribution',
    'hexRuin',
    'hexTheThirdSeal',
    'hexThrillOfTheHunt',
    'hexTwoCanPlay',
    'hexUndying',
    'hoarder',
    'hubris',
    'hysteria',
    'imAllEars',
    'infectiousFright',
    'insidious',
    'ironGrasp',
    'ironMaiden',
    'knockOut',
    'lethalPursuer',
    'leverage',
    'lightborn',
    'machineLearning',
    'madGrit',
    'makeYourChoice',
    'mercilessStorm',
    'mindbreaker',
    'monitorAndAbuse',
    'nemesis',
    'noWayOut',
    'nowhereToHide',
    'oppression',
    'overcharge',
    'overwhelmingPresence',
    'playWithYourFood',
    'popGoesTheWeasel',
    'predator',
    'rancor',
    'rapidBrutality',
    'rememberMe',
    'saveTheBestForLast',
    'scourgeHookFloodsOfRage',
    'scourgeHookGiftOfPain',
    'scourgeHookHangmansTrick',
    'scourgeHookMonstrousShrine',
    'scourgeHookPainResonance',
    'septicTouch',
    'shadowbord',
    'shatteredHope',
    'sloopyButcher',
    'spiesFromTheShadows',
    'spiritFury',
    'starstruck',
    'stridor',
    'superiorAnatomy',
    'surge',
    'surveillance',
    'terminus',
    'territorialImperative',
    'thanatophobia',
    'thrillingTremors',
    'thwack',
    'tinkerer',
    'trailOfTorment',
    'ultimateWeapon',
    'unbound',
    'undone',
    'unforeseen',
    'unnervingPresence',
    'unrelenting',
    'whispers',
    'zanshinTactics'
]; // list of all killers perks

const SURVIVOR_PERKS = [
    'aceInTheHole',
    'adrenaline',
    'aftercare',
    'alert',
    'anyMeansNecessary',
    'appraisal',
    'autodidact',
    'babysitter',
    'backgroundPlayer',
    'balancedLanding',
    'betterThanNew',
    'betterTogether',
    'biteTheBullet',
    'blastMine',
    'bloodPact',
    'bloodRush',
    'boilOver',
    'bond',
    'boonCircleOfHealing',
    'boonDarkTheory',
    'boonExponential',
    'boonIllumination',
    'boonShadowStep',
    'borrowedTime',
    'botanyKnowledge',
    'breakdown',
    'breakout',
    'buckleUp',
    'builtToLast',
    'calmSpirit',
    'camaraderie',
    'ChampionOfLight',
    'chemicalTrap',
    'clairvoyance',
    'correctiveAction',
    'counterforce',
    'cutLoose',
    'danceWithMe',
    'darkSense',
    'deadHard',
    'deadline',
    'deception',
    'decisiveStrike',
    'dejaVu',
    'deliverance',
    'desperateMeasures',
    'detectivesHunch',
    'distortion',
    'diversion',
    'dramaturgy',
    'empathicConnection',
    'empathy',
    'fastTrack',
    'fixated',
    'flashbang',
    'flip-Flop',
    'fogwise',
    'forThePeople',
    'friendlyCompetition',
    'headOn',
    'hope',
    'hyperfocus',
    'innerFocus',
    'innerStrength',
    'invocationWeavingSpiders',
    'ironWill',
    'kindred',
    'leader',
    'leftBehind',
    'light-Footed',
    'lightweight',
    'lithe',
    'lowProfile',
    'luckyBreak',
    'luckyStar',
    'madeForThis',
    'mettleOfMan',
    'noMither',
    'noOneLeftBehind',
    'objectOfObsession',
    'offTheRecord',
    'open-Handed',
    'overcome',
    'overzealous',
    'parentalGuidance',
    'pharmacy',
    'plotTwist',
    'plunderersInstinct',
    'poised',
    'potentialEnergy',
    'powerStruggle',
    'premonition',
    'proveThyself',
    'quickGambit',
    'reactiveHealing',
    'reassurance',
    'redHerring',
    'repressedAlliance',
    'residualManifest',
    'resilience',
    'resurgence',
    'rookieSpirit',
    'saboteur',
    'scavenger',
    'scenePartner',
    'secondWind',
    'self-Care',
    'self-Preservation',
    'slipperyMeat',
    'smallGame',
    'smashHit',
    'soleSurvivor',
    'solidarity',
    'soulGuard',
    'spineChill',
    'sprintBurst',
    'stakeOut',
    'streetwise',
    'strengthInShadows',
    'teamworkCollectiveStealth',
    'teamworkPowerOfTwo',
    'technician',
    'tenacity',
    'thisIsNotHappening',
    'troubleshooter',
    'unbreakable',
    'upTheAnte',
    'urbanEvasion',
    'vigil',
    'visionary',
    'wakeUp',
    'wellMakeIt',
    'wereGonnaLiveForever',
    'wicked',
    'windowsOfOpportunity',
    'wiretap'
]; // list of all survivor perks

const RARE_PERKS = [];

const KILLER_POWERS = {
    'trapper': {
        image: 'trap',
        addons: [
            { name: 'Bear Oil', image: 'bearOil', rarity: 'common', frenchName: 'Huile d\'ours' },
            { name: 'Makeshift Wrap', image: 'makeshiftWrap', rarity: 'common', frenchName: 'Écharpe Improvisée' },
            { name: 'Padded Jaws', image: 'paddedJaws', rarity: 'common', frenchName: 'Mâchoires Molletonnées' },
            { name: 'Trapper Gloves', image: 'trapperGloves', rarity: 'common', frenchName: 'Gants du Piégeur' },
            { name: '4-Coil Sprint Kit', image: '4-coilSpringKit', rarity: 'uncommon', frenchName: 'Kit à Quatre Ressorts' },
            { name: 'Coffee Grounds', image: 'coffeeGrounds', rarity: 'uncommon', frenchName: 'Café Moulu' },
            { name: 'Lengthened Jaws', image: 'lengthenedJaws', rarity: 'uncommon', frenchName: 'Mâchoires Allongées' },
            { name: 'Serrated Jaws', image: 'serratedJaws', rarity: 'uncommon', frenchName: 'Mâchoires Dentelées' },
            { name: 'Wax Brick', image: 'waxBrick', rarity: 'uncommon', frenchName: 'Brique de Cire' },
            { name: 'Fastening Tools', image: 'fasteningTools', rarity: 'rare', frenchName: 'Outils d\'Assemblage' },
            { name: 'Rusted Jaws', image: 'rustedJaws', rarity: 'rare', frenchName: 'Mâchoires Rouillées' },
            { name: 'Secondary Coil', image: 'secondaryCoil', rarity: 'rare', frenchName: 'Ressort Secondaire' },
            { name: 'Tar Bottle', image: 'tarBottle', rarity: 'rare', frenchName: 'Bouteille de Goudron' },
            { name: 'Trapper Bag', image: 'trapperBag', rarity: 'rare', frenchName: 'Sacoche du Piégeur' },
            { name: 'Honing Stone', image: 'honingStone', rarity: 'veryrare', frenchName: 'Pierre à Aiguiser' },
            { name: 'Oily Coil', image: 'oilyCoil', rarity: 'veryrare', frenchName: 'Ressort Huilé' },
            { name: 'Tension Spring', image: 'tensionSpring', rarity: 'veryrare', frenchName: 'Ressort à Tension' },
            { name: 'Trapper Sack', image: 'trapperSack', rarity: 'veryrare', frenchName: 'Sac du Piégeur' },
            { name: 'Bloody Coil', image: 'bloodyCoil', rarity: 'ultra', frenchName: 'Ressort Sanglant' },
            { name: 'Iridescent Stone', image: 'iridescentStone', rarity: 'ultra', frenchName: 'Pierre Irisée' }
        ]
    },
    'wraith': {
        image: 'bell',
        addons: [
            { name: '"The Beast" - Soot', image: 'theBeast-Soot', rarity: 'common', frenchName: '"La Bête" - Suie' },
            { name: '"The Ghost" - Soot', image: 'theGhost-Soot', rarity: 'common', frenchName: '"Ghost Face" - Suie' },
            { name: '"The Hound" - Soot', image: 'theHound-Soot', rarity: 'common', frenchName: '"Le Molosse" - Suie' },
            { name: '"The Serpent" - Soot', image: 'theSerpent-Soot', rarity: 'common', frenchName: '"Le Serpent" - Suie' },
            { name: '"Blind Warrior" - Mud', image: 'blindWarrior-Mud', rarity: 'uncommon', frenchName: '"Guerrier Aveugle" - Boue' },
            { name: '"Blink" - Mud', image: 'blink-Mud', rarity: 'uncommon', frenchName: '"Évanouissement" - Boue' },
            { name: '"Swift Hunt" - Mud', image: 'swiftHunt-Mud', rarity: 'uncommon', frenchName: '"Chasse Preste" - Boue' },
            { name: '"Windstorm" - Mud', image: 'windstorm-Mud', rarity: 'uncommon', frenchName: '"Tempête" - Boue' },
            { name: 'Bone Clapper', image: 'boneClapper', rarity: 'uncommon', frenchName: 'Battant en Os' },
            { name: '"Blind Warrior" - White', image: 'blindWarrior-White', rarity: 'rare', frenchName: '"Guerrier Aveugle" - Blanc' },
            { name: '"Blink" - White', image: 'blink-White', rarity: 'rare', frenchName: '"Évanouissement" - Blanc' },
            { name: '"Shadow Dance" - White', image: 'shadowDance-White', rarity: 'rare', frenchName: '"Danse de l\'Ombre" - Blanc' },
            { name: '"Swift Hunt" - White', image: 'swiftHunt-White', rarity: 'rare', frenchName: '"Chasse Preste" - Blanc' },
            { name: '"Windstorm" - White', image: 'windstorm-White', rarity: 'rare', frenchName: '"Tempête" - Blanc' },
            { name: '"All Seeing" - Blood', image: 'allSeeing-Blood', rarity: 'veryrare', frenchName: '"Clairvoyant" - Sang' },
            { name: '"Shadow Dance" - Blood', image: 'shadowDance-Blood', rarity: 'veryrare', frenchName: '"Danse de l\'Ombre" - Sang' },
            { name: '"Swift Hunt" - Blood', image: 'swiftHunt-Blood', rarity: 'veryrare', frenchName: '"Chasse Preste" - Sang' },
            { name: '"Windstorm" - Blood', image: 'windstorm-Blood', rarity: 'veryrare', frenchName: '"Tempête" - Sang' },
            { name: '"All Seeing" - Spirit', image: 'allSeeing-Spirit', rarity: 'ultra', frenchName: '"Clairvoyant" - Esprit' },
            { name: 'Coxcombed Clapper', image: 'coxcombedClapper', rarity: 'ultra', frenchName: 'Battant Encordé' }
        ]
    },
    'hillbilly': {
        image: 'chainsaw',
        addons: [
            { name: 'Counterweight', image: 'counterweight', rarity: 'common', frenchName: 'Contrepoids' },
            { name: 'Cracked Primer Bulb', image: 'crackedPrimerBulb', rarity: 'common', frenchName: 'Bulbe d\'Amorce Fissuré' },
            { name: 'Dad\'s Boots', image: 'dadsBoots', rarity: 'common', frenchName: 'Bottes de Papa' },
            { name: 'Steel Toe Boots', image: 'steelToeBoots', rarity: 'common', frenchName: 'Bottes à Embout d\'Acier' },
            { name: 'Clogged Intake', image: 'cloggedIntake', rarity: 'uncommon', frenchName: 'Entrée d\'Air Bouchée' },
            { name: 'Greased Throttle', image: 'greasedThrottle', rarity: 'uncommon', frenchName: 'Commande des Gaz Graissée' },
            { name: 'Off-Brand Motor Oil', image: 'off-BrandMotorOil', rarity: 'uncommon', frenchName: 'Huile Moteur Bon Marché' },
            { name: 'Spiked Boots', image: 'spikedBoots', rarity: 'uncommon', frenchName: 'Bottes à Pointes' },
            { name: 'Thermal Casing', image: 'thermalCasing', rarity: 'uncommon', frenchName: 'Revêtement Thermique' },
            { name: 'Begrimed Chains', image: 'begrimedChains', rarity: 'rare', frenchName: 'Chaînes Souillées' },
            { name: 'Low Kickback Chains', image: 'lowKickbackChains', rarity: 'rare', frenchName: 'Chaînes à Faible Recul' },
            { name: 'Ragged Engine', image: 'raggedEngine', rarity: 'rare', frenchName: 'Moteur Irrégulier' },
            { name: 'The Thompsons\' Mix', image: 'theThompsonsMix', rarity: 'rare', frenchName: 'Le Mélange des Thompson' },
            { name: 'Apex Muffler', image: 'apexMuffler', rarity: 'veryrare', frenchName: 'Silencieux de Pointe' },
            { name: 'Flithy Slippers', image: 'flithySlippers', rarity: 'veryrare', frenchName: 'Pantoufles Sales' },
            { name: 'High-Speed Idler Screw', image: 'high-SpeedIdlerScrew', rarity: 'veryrare', frenchName: 'Vis de Tendeur de Haut Régime' },
            { name: 'LoPro Chains', image: 'loProChains', rarity: 'veryrare', frenchName: 'Tronçonneuse Lo Pro' },
            { name: 'Iridescent Engravings', image: 'iridescentEngravings', rarity: 'ultra', frenchName: 'Gravures Irisées' },
            { name: 'Tuned Carburettor', image: 'tunedCarburettor', rarity: 'ultra', frenchName: 'Carburateur Réglé' }
        ]
    },
    'nurse': {
        image: 'breath',
        addons: [
            { name: 'Metal Spoon', image: 'metalSpoon', rarity: 'common', frenchName: 'Cuillère en Métal' },
            { name: 'Plaid Flannel', image: 'plaidFlannel', rarity: 'common', frenchName: 'Morceau de Plaid' },
            { name: 'White Nit Comb', image: 'whiteNitComb', rarity: 'common', frenchName: 'Peigne à Lentes Blanc' },
            { name: 'Wooden Horse', image: 'woodenHorse', rarity: 'common', frenchName: 'Cheval de Bois' },
            { name: 'Bad Man Keepsake', image: 'badManKeepsake', rarity: 'uncommon', frenchName: 'Souvenir du Méchant' },
            { name: 'Catatonic Boy\'s Treasure', image: 'catatonicBoysTreasure', rarity: 'uncommon', frenchName: 'Trésor d\'un Garçon Catatonique' },
            { name: 'Dark Cincture', image: 'darkCincture', rarity: 'uncommon', frenchName: 'Ceinture Obscure' },
            { name: 'Dull Bracelet', image: 'dullBracelet', rarity: 'uncommon', frenchName: 'Bracelet Terne' },
            { name: 'Pocket Watch', image: 'pocketWatch', rarity: 'uncommon', frenchName: 'Montre à Gousset' },
            { name: 'Anxious Gasp', image: 'anxiousGasp', rarity: 'rare', frenchName: 'Cri d\'Anxiété' },
            { name: 'Ataxic Respiration', image: 'ataxicRespiration', rarity: 'rare', frenchName: 'Respiration Ataxique' },
            { name: 'Fragile Wheeze', image: 'fragileWheeze', rarity: 'rare', frenchName: 'Respiration Difficile' },
            { name: 'Heavy Panting', image: 'heavyPanting', rarity: 'rare', frenchName: 'Halètement Intense' },
            { name: 'Spasmodic Breath', image: 'spasmodicBreath', rarity: 'rare', frenchName: 'Respiration Spasmodique' },
            { name: '"Bad Man\'s" Last Breath', image: 'badMansLastBreath', rarity: 'veryrare', frenchName: 'Dernier Souffle du "Méchant"' },
            { name: 'Campbell\'s Last Breath', image: 'campbellsLastBreath', rarity: 'veryrare', frenchName: 'Dernier Souffle de Campbell' },
            { name: 'Jenner\'s Last Breath', image: 'jennersLastBreath', rarity: 'veryrare', frenchName: 'Dernier Souffle de Jenner' },
            { name: 'Kavanagh\'s Last Breath', image: 'kavanaghsLastBreath', rarity: 'veryrare', frenchName: 'Dernier Souffle de Kavanagh' },
            { name: 'Matchbox', image: 'matchbox', rarity: 'ultra', frenchName: 'Boîte d\'Allumettes' },
            { name: 'Torn Bookmark', image: 'tornBookmark', rarity: 'ultra', frenchName: 'Signet Déchiré' }
        ]
    },
    'shape': {
        image: 'stalker1',
        addons: [
            { name: 'Blond Hair', image: 'blondHair', rarity: 'common', frenchName: 'Cheveux Blonds' },
            { name: 'Boyfriend\'s Memo', image: 'boyfriendsMemo', rarity: 'common', frenchName: 'Note du Petit Ami' },
            { name: 'Memorial Flower', image: 'memorialFlower', rarity: 'common', frenchName: 'Fleur Commémorative' },
            { name: 'Tacky Earrings', image: 'tackyEarrings', rarity: 'common', frenchName: 'Boucles d\'Oreilles Kitsch' },
            { name: 'Dead Rabbit', image: 'deadRabbit', rarity: 'uncommon', frenchName: 'Lapin Mort' },
            { name: 'Glass Fragment', image: 'glassFragment', rarity: 'uncommon', frenchName: 'Fragment de Verre' },
            { name: 'Hair Brush', image: 'hairBrush', rarity: 'uncommon', frenchName: 'Brosse à Cheveux' },
            { name: 'Jewellery', image: 'jewellery', rarity: 'uncommon', frenchName: 'Bijoux' },
            { name: 'Reflective Fragment', image: 'reflectiveFragment', rarity: 'uncommon', frenchName: 'Fragment Réfléchissant' },
            { name: 'Hair Bow', image: 'hairBow', rarity: 'rare', frenchName: 'Ruban' },
            { name: 'J. Myers Memorial', image: 'jMyersMemorial', rarity: 'rare', frenchName: 'Mémorial de J. Myers' },
            { name: 'Jewellery Box', image: 'jewelleryBox', rarity: 'rare', frenchName: 'Boite à Bijoux' },
            { name: 'Judith\'s Journal', image: 'judithsJournal', rarity: 'rare', frenchName: 'Journal de Judith' },
            { name: 'Mirror Shard', image: 'mirrorShard', rarity: 'rare', frenchName: 'Morceau de Miroir' },
            { name: 'Lock of Hair', image: 'lockOfHair', rarity: 'veryrare', frenchName: 'Mèche de Cheveux' },
            { name: 'Scratched Mirror', image: 'scratchedMirror', rarity: 'veryRare', frenchName: 'Miroir Rayé' },
            { name: 'Tombstone Piece', image: 'tombstonePiece', rarity: 'veryRare', frenchName: 'Morceau de Pierre Tombale' },
            { name: 'Vanity Mirror', image: 'vanityMirror', rarity: 'veryRare', frenchName: 'Miroir' },
            { name: 'Fragrant Tuft of Hair', image: 'fragrandTuftOfHair', rarity: 'ultra', frenchName: 'Touffe de Cheveux Parfumée' },
            { name: 'Judith\'s Tombstone', image: 'judithsTombstone', rarity: 'ultra', frenchName: 'Pierre Tombale de Judith' }
        ]
    },
    'hag': {
        image: 'blackenedCatalyst',
        addons: [
            { name: 'Bog Water', image: 'bogWater', rarity: 'common', frenchName: 'Eau du Bourbier' },
            { name: 'Dead Fly Mud', image: 'deadFlyMud', rarity: 'common', frenchName: 'Boue et Mouches Mortes' },
            { name: 'Powdered Eggshell', image: 'powderedEggshell', rarity: 'common', frenchName: 'Coquille d\'Oeuf Pulvérisée' },
            { name: 'Rope Necklet', image: 'ropeNecklet', rarity: 'common', frenchName: 'Collier en Corde' },
            { name: 'Bloodied Water', image: 'bloodiedWater', rarity: 'uncommon', frenchName: 'Eau Sanglante' },
            { name: 'Cypress Necklet', image: 'cypressNecklet', rarity: 'uncommon', frenchName: 'Collier en Cyprès' },
            { name: 'Dragonfly Wings', image: 'dragonflyWings', rarity: 'uncommon', frenchName: 'Ailes de Libellule' },
            { name: 'Half Eggshell', image: 'halfEggshell', rarity: 'uncommon', frenchName: 'Moitié de Coquille d\'Oeuf' },
            { name: 'Pussy Willow Catkins', image: 'pussyWillowCatkins', rarity: 'uncommon', frenchName: 'Chatons de Saulte' },
            { name: 'Bloodied Mud', image: 'bloodiedMud', rarity: 'rare', frenchName: 'Boue Sanglante' },
            { name: 'Cracked Turtle Egg', image: 'crackedTurtleEgg', rarity: 'rare', frenchName: 'Oeuf de Tortue Fêlé' },
            { name: 'Dried Cicada', image: 'driedCicada', rarity: 'rare', frenchName: 'Cigale Séchée' },
            { name: 'Swamp Orchid Necklet', image: 'swampOrchidNecklet', rarity: 'rare', frenchName: 'Collier d\'Orchidées des Marais' },
            { name: 'Willow Wreath', image: 'willowWreath', rarity: 'rare', frenchName: 'Couronne en Saule' },
            { name: 'Disfigured Ear', image: 'disfiguredEar', rarity: 'veryrare', frenchName: 'Oreille Déformée' },
            { name: 'Grandma\'s Heart', image: 'grandmasHeart', rarity: 'veryrare', frenchName: 'Coeur de Grand-Mère' },
            { name: 'Rusty Shackles', image: 'rustyshackles', rarity: 'veryrare', frenchName: 'Chaînes Rouillées' },
            { name: 'Scarred Hand', image: 'scarredHand', rarity: 'veryrare', frenchName: 'Main Balafrée' },
            { name: 'Mint Rag', image: 'mintRag', rarity: 'ultra', frenchName: 'Lambeau de Tissu Comme Neuf' },
            { name: 'Waterlogged Shoe', image: 'waterloggedShoe', rarity: 'ultra', frenchName: 'Chaussure Détrempée' }
        ]
    },
    'doctor': {
        image: 'cartersSpark',
        addons: [
            { name: '"Calm" - Class I', image: 'calm-ClassI', rarity: 'common', frenchName: '"Calme" - Cours I' },
            { name: '"Order" - Class I', image: 'order-ClassI', rarity: 'common', frenchName: '"Ordre" - Cours I' },
            { name: 'Maple Knight', image: 'mapleKnight', rarity: 'common', frenchName: 'Cavalier Érable' },
            { name: 'Mouldy Electrode', image: 'mouldyElectrode', rarity: 'common', frenchName: 'Vieille Électrode' },
            { name: '"Calm" - Class II', image: 'calm-ClassII', rarity: 'uncommon', frenchName: '"Calme" - Cours II' },
            { name: '"Discipline" - Class II', image: 'discipline-ClassII', rarity: 'uncommon', frenchName: '"Discipline" - Cours II' },
            { name: '"Order" - Class II', image: 'order-ClassII', rarity: 'uncommon', frenchName: '"Ordre" - Cours II' },
            { name: '"Restraint" - Class II', image: 'restraint-ClassII', rarity: 'uncommon', frenchName: '"Contrainte" - Cours II' },
            { name: 'Polished Electrode', image: 'polishedElectrode', rarity: 'uncommon', frenchName: 'Électrode Brillante' },
            { name: '"Discipline" - Class III', image: 'discipline-ClassIII', rarity: 'rare', frenchName: '"Discipline" - Cours III' },
            { name: '"Restraint" - Class III', image: 'restraint-ClassIII', rarity: 'rare', frenchName: '"Contrainte" - Cours III' },
            { name: 'High Stimulus Electrode', image: 'highStimulusElectrode', rarity: 'rare', frenchName: 'Électrode à Stimulation Élevée' },
            { name: 'Interview Tape', image: 'interviewTape', rarity: 'rare', frenchName: 'Cassette d\'Entretient'},
            { name: 'Scrapped Tape', image: 'scrappedTape', rarity: 'rare', frenchName: 'Cassette Abîmée' },
            { name: '"Calm" - Carter\'s Notes', image: 'calm-CartersNotes', rarity: 'veryrare', frenchName: '"Calme" - Notes de Carter' },
            { name: '"Discipline" - Carter\'s Notes', image: 'discipline-CartersNotes', rarity: 'veryrare', frenchName: '"Discipline" - Notes de Carter' },
            { name: '"Order" - Carter\'s Notes', image: 'order-CartersNotes', rarity: 'veryrare', frenchName: '"Ordre" - Notes de Carter' },
            { name: '"Restraint" - Carter\'s Notes', image: 'restraint-CartersNotes', rarity: 'veryrare', frenchName: '"Contrainte" - Notes de Carter' },
            { name: 'Iridescent King', image: 'iridescentKing', rarity: 'ultra', frenchName: 'Roi Irisé' },
            { name: 'Iridescent Queen', image: 'iridescentQueen', rarity: 'ultra', frenchName: 'Reine Irisée' }
        ]
    },
    'huntress': {
        image: 'huntingHatchets',
        addons: [
            { name: 'Amanita Toxin', image: 'amanitaToxin', rarity: 'common', frenchName: 'Toxine d\'Amanite' },
            { name: 'Bandaged Haft', image: 'bandagedHaft', rarity: 'common', frenchName: 'Manche Bandé' },
            { name: 'Coarse Stone', image: 'coarseStone', rarity: 'common', frenchName: 'Pierre Grossière' },
            { name: 'Yellowed Cloth', image: 'yellowedCloth', rarity: 'common', frenchName: 'Tissu Jaune' },
            { name: 'Leather Loop', image: 'leatherLoop', rarity: 'uncommon', frenchName: 'Boucle en Cuir' },
            { name: 'Manna Grass Braid', image: 'mannaGrassBraid', rarity: 'uncommon', frenchName: 'Tresse de Glycérie' },
            { name: 'Oak Haft', image: 'oakHaft', rarity: 'uncommon', frenchName: 'Manche en Chêne' },
            { name: 'Shiny Pin', image: 'shinyPin', rarity: 'uncommon', frenchName: 'Épingle Brillante' },
            { name: 'Weighted Head', image: 'weightedHead', rarity: 'uncommon', frenchName: 'Tête Lestée' },
            { name: 'Deerskin Gloves', image: 'deerskinGloves', rarity: 'rare', frenchName: 'Gants en Peau de Daim' },
            { name: 'Flower Babushka', image: 'flowerBabushka', rarity: 'rare', frenchName: 'Poupée Russe à Fleurs' },
            { name: 'Rose Root', image: 'roseRoot', rarity: 'rare', frenchName: 'Racine de Rose' },
            { name: 'Rusty Head', image: 'rustyHead', rarity: 'rare', frenchName: 'Tête Rouillée' },
            { name: 'Venomous Concoction', image: 'venomousConcoction', rarity: 'rare', frenchName: 'Concoction Vénéneuse' },
            { name: 'Begrimed Head', image: 'begrimedHead', rarity: 'veryrare', frenchName: 'Tête Souillée' },
            { name: 'Glowing Concoction', image: 'glowingConcoction', rarity: 'veryrare', frenchName: 'Concoction Luisante' },
            { name: 'Infantry Belt', image: 'infantryBelt', rarity: 'veryrare', frenchName: 'Ceinture d\'Infanterie' },
            { name: 'Wooden Fox', image: 'woodenFox', rarity: 'veryrare', frenchName: 'Renard de Bois' },
            { name: 'Iridescent Head', image: 'iridescentHead', rarity: 'ultra', frenchName: 'Tête Irisée' },
            { name: 'Soldier\'s Puttee', image: 'soldiersPuttee', rarity: 'ultra', frenchName: 'Bande Molletière de Soldat' }
        ]
    },
    'cannibal': {
        image: 'bubbasChainsaw',
        addons: [
            { name: 'Chainsaw File', image: 'chainsawFile', rarity: 'common', frenchName: 'Aiguiseur de Chaîne' },
            { name: 'Spark Plug', image: 'sparkPlug', rarity: 'common', frenchName: 'Bougie d\'Allumage' },
            { name: 'Speed Limiter', image: 'speedLimiter', rarity: 'common', frenchName: 'Limiteur de Vitesse' },
            { name: 'Vegetable Oil', image: 'vegetableOil', rarity: 'common', frenchName: 'Huile Végétale' },
            { name: 'Chilli', image: 'chilli', rarity: 'uncommon', frenchName: 'Chili' },
            { name: 'Homemade Muffler', image: 'homemadeMuffler', rarity: 'uncommon', frenchName: 'Silencieux Fait Maison' },
            { name: 'Knife Scratches', image: 'knifeScratches', rarity: 'uncommon', frenchName: 'Griffures de Couteau' },
            { name: 'Long Guide Bar', image: 'longGuideBar', rarity: 'uncommon', frenchName: 'Guide Allongé' },
            { name: 'Primer Bulb', image: 'primerBulb', rarity: 'uncommon', frenchName: 'Poire d\'Amorçage' },
            { name: 'Begrimed Chains', image: 'begrimedChains', rarity: 'rare', frenchName: 'Chaînes Souillées' },
            { name: 'Grisly Chains', image: 'grislyChains', rarity: 'rare', frenchName: 'Chaîne Macabre' },
            { name: 'Shop Lubricant', image: 'shopLubricant', rarity: 'rare', frenchName: 'Lubrifiant d\'Atelier' },
            { name: 'The Beast\'s Marks', image: 'theBeastsMarks', rarity: 'rare', frenchName: 'Les Marques de la Bête' },
            { name: 'The Grease', image: 'theGrease', rarity: 'rare', frenchName: 'La Graisse' },
            { name: 'Award-winning Chilli', image: 'award-winningChilli', rarity: 'veryrare', frenchName: 'Chili Primé' },
            { name: 'Depth Gauge Rake', image: 'depthGaugeRake', rarity: 'veryrare', frenchName: 'Allonge de Profondeur' },
            { name: 'Light Chassis', image: 'lightChassis', rarity: 'veryrare', frenchName: 'Châssis Léger' },
            { name: 'Rusted Chains', image: 'rustedChains', rarity: 'veryrare', frenchName: 'Chaîne Rouillée' },
            { name: 'Carburettor Tuning Guide', image: 'carburettorTuningGuide', rarity: 'ultra', frenchName: 'Guide de Réglage de Carburateur' },
            { name: 'Iridescent Flesh', image: 'iridescentFlesh', rarity: 'ultra', frenchName: 'Chair Irisée' }
        ]
    },
    'nightmare': {
        image: 'dreamDemon',
        addons: [
            { name: 'Garden Rake', image: 'gardenRake', rarity: 'common', frenchName: 'Râteau' },
            { name: 'Kid\'s Drawing', image: 'kidsDrawing', rarity: 'common', frenchName: 'Dessin d\'Enfant' },
            { name: 'Sheep Block', image: 'sheepBlock', rarity: 'common', frenchName: 'Bloc Mouton' },
            { name: 'Wool Shirt', image: 'woolShirt', rarity: 'common', frenchName: 'Maillot en Laine' },
            { name: 'Cat Block', image: 'catBlock', rarity: 'uncommon', frenchName: 'Bloc Chat' },
            { name: 'Green Dress', image: 'greenDress', rarity: 'uncommon', frenchName: 'Robe Verte' },
            { name: 'Nancy\'s Sketch', image: 'nancysSketch', rarity: 'uncommon', frenchName: 'Croquis de Nancy' },
            { name: 'Outdoor Rope', image: 'outdoorRope', rarity: 'uncommon', frenchName: 'Corde de Randonnée' },
            { name: 'Prototype Claws', image: 'prototypeClaws', rarity: 'uncommon', frenchName: 'Prototype de Griffes' },
            { name: 'Blue Dress', image: 'blueDress', rarity: 'rare', frenchName: 'Robe Bleue' },
            { name: 'Jump Rope', image: 'jumpRope', rarity: 'rare', frenchName: 'Corde à Sauter' },
            { name: 'Nancy\'s Masterpiece', image: 'NancysMasterpiece', rarity: 'rare', frenchName: 'Chef-d\'Oeuvre de Nancy' },
            { name: 'Paint Thinner', image: 'paintThinner', rarity: 'rare', frenchName: 'Diluant à Peinture' },
            { name: 'Unicorn Block', image: 'unicornBlock', rarity: 'rare', frenchName: 'Bloc Licorne' },
            { name: '"Z" Block', image: 'zBlock', rarity: 'veryrare', frenchName: 'Bloc "Z"' },
            { name: 'Class Photo', image: 'classPhoto', rarity: 'veryrare', frenchName: 'Photo de Classe' },
            { name: 'Pill Bottle', image: 'pillBottle', rarity: 'veryrare', frenchName: 'Flacon de Cachets' },
            { name: 'Swing Chains', image: 'swingChains', rarity: 'veryrare', frenchName: 'Chaînes de Balançoire' },
            { name: 'Black Box', image: 'blackBox', rarity: 'ultra', frenchName: 'Boîte Noire' },
            { name: 'Red Paint Brush', image: 'redPaintBrush', rarity: 'ultra', frenchName: 'Pinceau avec Peinture Rouge' }
        ]
    },
    'pig': {
        image: 'jigsawsBaptism',
        addons: [
            { name: 'Combat Straps', image: 'combatStraps', rarity: 'common', frenchName: 'Sangles de Combat' },
            { name: 'Interlocking Razor', image: 'interlockingRazor', rarity: 'common', frenchName: 'Rasoirs Enchevêtrés' },
            { name: 'John\'s Medical File', image: 'JohnsMedicalFile', rarity: 'common', frenchName: 'Dossier Médical de John' },
            { name: 'Shattered Syringe', image: 'shatteredSyringe', rarity: 'common', frenchName: 'Seringue Brisée' },
            { name: 'Face Mask', image: 'faceMask', rarity: 'uncommon', frenchName: 'Masque' },
            { name: 'Last Will', image: 'lastWill', rarity: 'uncommon', frenchName: 'Testament' },
            { name: 'Razor Wires', image: 'razorWires', rarity: 'uncommon', frenchName: 'Fil Barbelé' },
            { name: 'Utility Blades', image: 'utilityBlades', rarity: 'uncommon', frenchName: 'Lames de Cutter' },
            { name: 'Workshop Grease', image: 'workshopGrease', rarity: 'uncommon', frenchName: 'Lubrifiant' },
            { name: 'Bag of Gears', image: 'bagOfGears', rarity: 'rare', frenchName: 'Sac de Rouages' },
            { name: 'Jigsaw\'s Annotated Plan', image: 'jigsawsAnnotatedPlan', rarity: 'rare', frenchName: 'Croquis Annoté de Jigsaw' },
            { name: 'Rules Set No.2', image: 'rulesSetNo2', rarity: 'rare', frenchName: 'Ensemble de Règles N°2' },
            { name: 'Rusty Attachments', image: 'rustyAttachments', rarity: 'rare', frenchName: 'Dents Rouillées' },
            { name: 'Slow-Release Toxin', image: 'slow-ReleaseToxin', rarity: 'rare', frenchName: 'Toxine à Libération Lente' },
            { name: 'Amanda\'s Secret', image: 'amandasSecret', rarity: 'veryrare', frenchName: 'Secret d\'Amanda' },
            { name: 'Crate of Gears', image: 'crateOfGears', rarity: 'veryrare', frenchName: 'Caisse de Rouages' },
            { name: 'Jigsaw\'s Sketch', image: 'jigsawsSketch', rarity: 'veryrare', frenchName: 'Croquis de Jigsaw' },
            { name: 'Tampered Timer', image: 'tamperedTimer', rarity: 'veryrare', frenchName: 'Minuteur Trafiqué' },
            { name: 'Amanda\'s Letter', image: 'amandasLetter', rarity: 'ultra', frenchName: 'Lettre à Amanda' },
            { name: 'Video Tape', image: 'videoTape', rarity: 'ultra', frenchName: 'Cassette Vidéo' }
        ]
    },
    'clown': {
        image: 'gasBomb',
        addons: [
            { name: 'Fingerless Parade Gloves', image: 'fingerlessParadeGloves', rarity: 'common', frenchName: 'Mitaines de Parade' },
            { name: 'Party Bottle', image: 'partyBottle', rarity: 'common', frenchName: 'Bouteille de Fête' },
            { name: 'Robin Feather', image: 'robinFeather', rarity: 'common', frenchName: 'Plume de Rouge-Gorge' },
            { name: 'VHS Porn', image: 'vhsPorn', rarity: 'common', frenchName: 'VHS Porn' },
            { name: 'Kerosene Can', image: 'keroseneCan', rarity: 'uncommon', frenchName: 'Bidon de Kérosène' },
            { name: 'Solvent Jug', image: 'solventJug', rarity: 'uncommon', frenchName: 'Bidon de Solvant' },
            { name: 'Starling Feather', image: 'starlingFeather', rarity: 'uncommon', frenchName: 'Plume d\'Étourneau' },
            { name: 'Sticky Soda Bottle', image: 'stickySodaBottle', rarity: 'uncommon', frenchName: 'Bouteille de Soda Collante' },
            { name: 'Thick Cork Stopper', image: 'thickCorkStopper', rarity: 'uncommon', frenchName: 'Bouchon Épais' },
            { name: 'Bottle of Chloroform', image: 'bottleOfChloroform', rarity: 'rare', frenchName: 'Bouteille de Chloroforme' },
            { name: 'Flask of Bleach', image: 'flaskOfBleach', rarity: 'rare', frenchName: 'Flacon de Détergent' },
            { name: 'Smelly Inner Soles', image: 'smellyInnerSoles', rarity: 'rare', frenchName: 'Semelles Intérieures Puantes' },
            { name: 'Spirit of Hartshorn', image: 'spiritOfHartshorn', rarity: 'rare', frenchName: 'Esprit de Hartshorn' },
            { name: 'Sulphuric Acid Vial', image: 'sulphuricAcidVial', rarity: 'rare', frenchName: 'Flacon d\'Acide Sulfurique' },
            { name: 'Cheap Gin Bottle', image: 'cheapGinBottle', rarity: 'veryrare', frenchName: 'Bouteille de Gin Bon Marché' },
            { name: 'Cigar Box', image: 'cigarBox', rarity: 'veryrare', frenchName: 'Boîte à Cigares' },
            { name: 'Ether 15 Vol%', image: 'ether15Vol%', rarity: 'veryrare', frenchName: 'Éther à 15 % du Volume' },
            { name: 'Garish Make-Up Kit', image: 'garishMake-UpKit', rarity: 'veryrare', frenchName: 'Boîte à Maquillage Criard' },
            { name: 'Redhead\'s Pinkie Finger', image: 'redheadsPinkieFinger', rarity: 'ultra', frenchName: 'Petit Doigt de Personne Rousse' },
            { name: 'Tattoo\'s Middle Finger', image: 'tattoosMiddleFinger', rarity: 'ultra', frenchName: 'Majeur du Tatoué' }
        ]
    },
    'spirit': {
        image: 'yamaokasHaunting',
        addons: [
            { name: 'Gifted Bamboo Comb', image: 'giftedBambooComb', rarity: 'common', frenchName: 'Peigne en Bambou Offert' },
            { name: 'Origami Crane', image: 'origamiCrane', rarity: 'common', frenchName: 'Grue en Origami' },
            { name: 'Shiawase Amulet', image: 'shiawaseAmulet', rarity: 'common', frenchName: 'Amulette Porte-Bonheur' },
            { name: 'Zori', image: 'zori', rarity: 'common', frenchName: 'Zori' },
            { name: 'Juniper Bonsai', image: 'juniperBonsai', rarity: 'uncommon', frenchName: 'Bonsaï de Genévrier' },
            { name: 'Kalun Talisman', image: 'kalunTalisman', rarity: 'uncommon', frenchName: 'Talisman de Chance' },
            { name: 'Muddy Sports Day Cap', image: 'muddySportsDayCap', rarity: 'uncommon', frenchName: 'Casquette de Sport Boueuse' },
            { name: 'Rin\'s Broken Watch', image: 'rinsBrokenWatch', rarity: 'uncommon', frenchName: 'Montre Cassée de Rin' },
            { name: 'White Hair Ribbon', image: 'whiteHairRibbon', rarity: 'uncommon', frenchName: 'Ruban Blanc pour Cheveux' },
            { name: 'Katana Tsuba', image: 'katanaTsuba', rarity: 'rare', frenchName: 'Tsuba pour Katana' },
            { name: 'Mother\'s Glasses', image: 'mothersGlasses', rarity: 'rare', frenchName: 'Lunettes de Mère' },
            { name: 'Rusty Flute', image: 'rustyFlute', rarity: 'rare', frenchName: 'Flûte Rouillée' },
            { name: 'Senko Hanabi', image: 'senkoHanabi', rarity: 'rare', frenchName: 'Senko Hanabi' },
            { name: 'Uchiwa', image: 'uchiwa', rarity: 'rare', frenchName: 'Uchiwa' },
            { name: 'Dried Cherry Blossom', image: 'driedCherryBlossom', rarity: 'veryrare', frenchName: 'Fleur de Cerisier Séchée' },
            { name: 'Furin', image: 'furin', rarity: 'veryrare', frenchName: 'Furin' },
            { name: 'Wakizashi Saya', image: 'wakizashiSaya', rarity: 'veryrare', frenchName: 'Fourreau de Wakizashi' },
            { name: 'Yakuyoke Amulet', image: 'yakuyokeAmulet', rarity: 'veryrare', frenchName: 'Amulette Yakuyoke' },
            { name: 'Kintsugi Teacup', image: 'kintsugiTeacup', rarity: 'ultra', frenchName: 'Tasse à Thé Kintsugi' },
            { name: 'Mother-Daughter Ring', image: 'mother-DaughterRing', rarity: 'ultra', frenchName: 'Bage Mère-Fille' }
        ]
    },
    'legion': {
        image: 'feralFrenzy',
        addons: [
            { name: 'Friendship Bracelet', image: 'friendshipBracelet', rarity: 'common', frenchName: 'Bracelet d\'Amitié' },
            { name: 'Mischief List', image: 'mischiefList', rarity: 'common', frenchName: 'Liste de Méfaits' },
            { name: 'Scratched Ruler', image: 'scratchedRuler', rarity: 'common', frenchName: 'Règle Éraflée' },
            { name: 'Smiley Face Pin', image: 'smileyFacePin', rarity: 'common', frenchName: 'Badge Smiley' },
            { name: 'Defaced Smiley Pin', image: 'defacedSmiley', rarity: 'uncommon', frenchName: 'Badge Smiley Défiguré' },
            { name: 'Etched Ruler', image: 'etchedRuler', rarity: 'uncommon', frenchName: 'Règle Entaillée' },
            { name: 'Julie\'s Mix Tape', image: 'juliesMixTape', rarity: 'uncommon', frenchName: 'Cassette de Musique' },
            { name: 'Mural Sketch', image: 'muralSketch', rarity: 'uncommon', frenchName: 'Fresque' },
            { name: 'Never-Sleep Pills', image: 'never-SleepPills', rarity: 'uncommon', frenchName: 'Cachets Anti-Sommeil' },
            { name: 'Joey\'s Mix Tape', image: 'joeysMixTape', rarity: 'rare', frenchName: 'Cassette de Musique de Susie' },
            { name: 'Stolen Sketch Book', image: 'StolenSketchBook', rarity: 'rare', frenchName: 'Carnet à Dessin Volé' },
            { name: 'Stylish Sunglasses', image: 'stylishSunglasses', rarity: 'rare', frenchName: 'Lunettes de Soleil Stylées' },
            { name: 'BFFs', image: 'bffs', rarity: 'veryrare', frenchName: 'Amis pour la Vie' },
            { name: 'Flithy Blade', image: 'flithyBlade', rarity: 'veryrare', frenchName: 'Lame Dégoûtante' },
            { name: 'Frank\'s Mix Tape', image: 'franksMixTape', rarity: 'veryrare', frenchName: 'Cassette de Musique de Frank' },
            { name: 'Stab Wounds Study', image: 'stabWoundsStudy', rarity: 'veryrare', frenchName: 'Étude sur les Blessures par Arme Blanche' },
            { name: 'Fuming Mix Tape', image: 'fumingMixTape', rarity: 'ultra', frenchName: 'Cassette de Musique Fumante' },
            { name: 'Iridescent Button', image: 'iridescentButton', rarity: 'ultra', frenchName: 'Badge Irisé' }
        ]
    },
    'plague': {
        image: 'vilePurge',
        addons: [
            { name: 'Healing Salve', image: 'healingSalve', rarity: 'common', frenchName: 'Baume de Soins' },
            { name: 'Limestone Seal', image: 'limestoneSeal', rarity: 'common', frenchName: 'Sceau Calcaire' },
            { name: 'Olibanum Incense', image: 'olibanumIncense', rarity: 'common', frenchName: 'Olibanum' },
            { name: 'Prayer Tablet Fragment', image: 'prayerTabletFragment', rarity: 'common', frenchName: 'Fragment de Tablette de Prière' },
            { name: 'Blessed Apple', image: 'blessedApple', rarity: 'uncommon', frenchName: 'Pomme Bénie' },
            { name: 'Emetic Potion', image: 'emeticPotion', rarity: 'uncommon', frenchName: 'PotionVomitive' },
            { name: 'Haematite Seal', image: 'haematiteSeal', rarity: 'uncommon', frenchName: 'Sceau d\'Hématite' },
            { name: 'Potent Tincture', image: 'potentTincture', rarity: 'uncommon', frenchName: 'Teinture Forte' },
            { name: 'Prophylactic Amulet', image: 'prophylacticAmulet', rarity: 'uncommon', frenchName: 'Amulette Prophylactique' },
            { name: 'Ashen Apple', image: 'ashenApple', rarity: 'rare', frenchName: 'Pomme Grisâtre' },
            { name: 'Exorcism Amulet', image: 'exorcismAmulet', rarity: 'rare', frenchName: 'Amulette d\'Exorcisme' },
            { name: 'Incensed Ointment', image: 'incensedOintment', rarity: 'rare', frenchName: 'Onguent Odorant' },
            { name: 'Infected Emetic', image: 'infectedEmetic', rarity: 'rare', frenchName: 'Vomi Infecté' },
            { name: 'Rubbing Oil', image: 'rubbingOil', rarity: 'rare', frenchName: 'Huile de Massage' },
            { name: 'Devotee\'s Amulet', image: 'devoteesAmulet', rarity: 'veryrare', frenchName: 'Amulette de l\'Adepte' },
            { name: 'Severed Toe', image: 'severedToe', rarity: 'veryrare', frenchName: 'Orteil Tranché' },
            { name: 'Vile Emetic', image: 'vileEmetic', rarity: 'veryrare', frenchName: 'Vomitif Abominable' },
            { name: 'Worship Tablet', image: 'worshipTablet', rarity: 'veryrare', frenchName: 'Tablette d\'Adoration' },
            { name: 'Black Incense', image: 'blackIncense', rarity: 'ultra', frenchName: 'Encens Noir' },
            { name: 'Iridescent Seal', image: 'iridescentSeal', rarity: 'ultra', frenchName: 'Sceau Irisé' }
        ]
    },
    'ghostface': {
        image: 'nightShroud',
        addons: [
            { name: '"Philly"', image: 'philly', rarity: 'common', frenchName: '"Philly"' },
            { name: 'Cheap Cologne', image: 'cheapCologne', rarity: 'common', frenchName: 'Eau de Cologne Bon Marché' },
            { name: 'Headline Cut-Outs', image: 'headlineCut-Outs', rarity: 'common', frenchName: 'Coupures de Presse' },
            { name: 'Walleye\'s Matchbook', image: 'walleyesMatchbook', rarity: 'common', frenchName: 'Allumettes du Walleye' },
            { name: 'Cinch Straps', image: 'cinchStraps', rarity: 'uncommon', frenchName: 'Sangles' },
            { name: 'Marked Map', image: 'markedMap', rarity: 'uncommon', frenchName: 'Carte Marquée' },
            { name: 'Olsen\'s Address Book', image: 'olsensAddressBook', rarity: 'uncommon', frenchName: 'Carnet d\'Adresses d\'Olsen' },
            { name: 'Olsen\'s Journal', image: 'olsensJournal', rarity: 'uncommon', frenchName: 'Journal d\'Olsen' },
            { name: 'Telephoto Lens', image: 'telephotoLens', rarity: 'uncommon', frenchName: 'Téléobjectif' },
            { name: 'Chewed Pen', image: 'chewedPen', rarity: 'rare', frenchName: 'Stylo Mâchouillé' },
            { name: 'Knife Belt Clip', image: 'knifeBeltClip', rarity: 'rare', frenchName: 'Étui de Ceinture à Couteau' },
            { name: 'Lasting Perfume', image: 'lastingPerfume', rarity: 'rare', frenchName: 'Parfum Durable' },
            { name: 'Leather Knife Sheath', image: 'leatherKnifeSheath', rarity: 'rare', frenchName: 'Fourreau de Couteau en Cuir' },
            { name: 'Olsen\'s Wallet', image: 'olsensWallet', rarity: 'rare', frenchName: 'Porte-Feuille d\'Olsen' },
            { name: 'Driver\'s License', image: 'Permis de Conduire', rarity: 'veryrare', frenchName: 'Permis de Conduire' },
            { name: 'Drop-Leg Knife Sheath', image: 'drop-LegKnifeSheath', rarity: 'veryrare', frenchName: 'Fourreau de Couteau Fixe' },
            { name: 'Night Vision Monocular', image: 'nightVisionMonocular', rarity: 'veryrare', frenchName: 'Objectif de Vision Nocturne' },
            { name: 'Victim\'s Detailed Routine', image: 'victimsDetailedRoutine', rarity: 'veryrare', frenchName: 'Routine Détaillée de la Victime' },
            { name: '"Ghost Face Caught on Tape"', image: 'ghostFaceCaughtOnTape', rarity: 'ultra', frenchName: '"Ghost Face Surpris en Direct"' },
            { name: 'Outdoor Security Camera', image: 'outdoorSecurityCamera', rarity: 'ultra', frenchName: 'Caméra de Sécurité Extérieure' }
        ]
    },
    'demogorgon': {
        image: 'ofTheAbyss',
        addons: [
            { name: 'Black Heart', image: 'blackHeart', rarity: 'common', frenchName: 'Coeur Noir' },
            { name: 'Rat Liver', image: 'ratLiver', rarity: 'common', frenchName: 'Foie de Rat' },
            { name: 'Rat Tail', image: 'ratTail', rarity: 'common', frenchName: 'Queue de Rat' },
            { name: 'Rotten Pumpkin', image: 'rottenPumpkin', rarity: 'common', frenchName: 'Citrouille Pourrie' },
            { name: 'Barb\'s Glasses', image: 'barbsGlasses', rarity: 'uncommon', frenchName: 'Lunettes de Barb' },
            { name: 'Mews\' Guts', image: 'mewsGuts', rarity: 'uncommon', frenchName: 'Boyaux de Miaou' },
            { name: 'Rotten Green Tripe', image: 'rottenGreenTripe', rarity: 'uncommon', frenchName: 'Tripes Vertes Décomposées' },
            { name: 'Sticky Lining', image: 'stickyLining', rarity: 'uncommon', frenchName: 'Revêtement Gluant' },
            { name: 'Viscous Webbing', image: 'viscousWebbing', rarity: 'uncommon', frenchName: 'Toile Visqueuse' },
            { name: 'Brass Case Lighter', image: 'brassCaseLighter', rarity: 'rare', frenchName: 'Briquet en Cuivre' },
            { name: 'Deer Lung', image: 'deerLung', rarity: 'rare', frenchName: 'Poumon de Biche' },
            { name: 'Eleven\'s Soda', image: 'elevensSoda', rarity: 'rare', frenchName: 'Soda de Onze' },
            { name: 'Thorny Vines', image: 'thornyVines', rarity: 'rare', frenchName: 'Lianes Épineuses' },
            { name: 'Violet Waxcap', image: 'violetWaxcap', rarity: 'rare', frenchName: 'Bonnet Cireux Violet' },
            { name: 'Lifeguard Whistle', image: 'lifeguardWhistle', rarity: 'veryrare', frenchName: 'Sifflet de Maître-Nageur' },
            { name: 'Unknown Egg', image: 'unknownEgg', rarity: 'veryrare', frenchName: 'Oeuf Inconnu' },
            { name: 'Upside Down Resin', image: 'upsideDownResin', rarity: 'veryrare', frenchName: 'Résine Sens Dessus Dessous' },
            { name: 'Vermillon Webcap', image: 'vermillonWebcap', rarity: 'veryrare', frenchName: 'Petit Bonnet Vermillon' },
            { name: 'Leprose Lichen', image: 'leproseLichen', rarity: 'ultra', frenchName: 'Lichen Lépreux' },
            { name: 'Red Moss', image: 'redMoss', rarity: 'ultra', frenchName: 'Mousse Rouge' }
        ]
    },
    'oni': {
        image: 'yamaokasWrath',
        addons: [
            { name: 'Blackened Toenail', image: 'blackenedToenail', rarity: 'common', frenchName: 'Ongle de Pied Noirci' },
            { name: 'Cracked Sakazuki', image: 'crackedSakazuki', rarity: 'common', frenchName: 'Sakazuki Fêlée' },
            { name: 'Paper Lantern', image: 'paperLantern', rarity: 'common', frenchName: 'Lanterne en Papier' },
            { name: 'Rotting Rope', image: 'rottingRope', rarity: 'common', frenchName: 'Corde en Décomposition' },
            { name: 'Bloody Sash', image: 'bloodySash', rarity: 'uncommon', frenchName: 'Écharpe Sanglante' },
            { name: 'Child\'s Wooden Sword', image: 'childsWoodenSword', rarity: 'uncommon', frenchName: 'Épée de Bois d\'Enfant' },
            { name: 'Chipped Salhal', image: 'chippedSalhal', rarity: 'uncommon', frenchName: 'Salhal Ébréché' },
            { name: 'Ink Lion', image: 'inkLion', rarity: 'uncommon', frenchName: 'Lion à l\'Encre' },
            { name: 'Polished Maedate', image: 'polishedMaedate', rarity: 'uncommon', frenchName: 'Maedate Lustré' },
            { name: 'Kanal-Anzen Talisman', image: 'kanal-Anzen Talisman', rarity: 'rare', frenchName: 'Talisman Kanal-Anzen' },
            { name: 'Scalped Topknot', image: 'scalpedTopknot', rarity: 'rare', frenchName: 'Chignon Scalpé' },
            { name: 'Shattered Wakizashi', image: 'shatteredWakizashi', rarity: 'rare', frenchName: 'Wakizashi Brisé' },
            { name: 'Wooden Oni Mask', image: 'woodenOniMask', rarity: 'rare', frenchName: 'Masque d\'Oni en Bois' },
            { name: 'Yamaoka Sashimono', image: 'yamaokaSashimono', rarity: 'rare', frenchName: 'Yamaoka Sashimono' },
            { name: 'Akito\'s Crutch', image: 'akitosCrutch', rarity: 'veryrare', frenchName: 'Béquille d\'Akito' },
            { name: 'Lion Fang', image: 'lionFang', rarity: 'veryrare', frenchName: 'Croc de Lion' },
            { name: 'Splintered Hull', image: 'splinteredHull', rarity: 'veryrare', frenchName: 'Coque Éventrée' },
            { name: 'Tear-Soaked Tenugul', image: 'tear-SoakedTenugul', rarity: 'veryrare', frenchName: 'Tenugul Imbibé de Larmes' },
            { name: 'Iridescent Family Crest', image: 'iridescentFamilyCrest', rarity: 'ultra', frenchName: 'Blason de Famille Irisé' },
            { name: 'Renjiro\'s Bloody Glove', image: 'renjirosBloodyGlove', rarity: 'ultra', frenchName: 'Gant Sanglant de Renjiro' }
        ]
    }
}
