const ROLES = [
    'killer',
    'survivor'
];

const SURVIVORS = [
    'dwight',
    'meg',
    'claudette',
    'jake',
    'nea',
    'laurie',
    'ace',
    'bill',
    'feng',
    'david',
    'quentin',
    'tapp',
    'kate',
    'adam',
    'jeff',
    'jane',
    'ash',
    'nancy',
    'steve',
    'yui',
    'zarina',
    'cheryl',
    'felix',
    'elodie',
    'yun',
    'jill',
    'leon',
    'mikaela',
    'jonah',
    'yoichi',
    'haddie',
    'ada',
    'rebecca',
    'vittorio',
    'thalita',
    'renato',
    'gabriel',
    'nicolas',
    'ellen',
    'alan',
    'sable'
]; // list of all available survivors

const KILLERS = [
    'trapper',
    'wraith',
    'hillbilly',
    'nurse',
    'shape',
    'hag',
    'doctor',
    'huntress',
    'cannibal',
    'nightmare',
    'pig',
    'clown',
    'spirit',
    'legion',
    'plage',
    'ghostface',
    'demogorgon',
    'oni',
    'deathslinger',
    'executioner',
    'blight',
    'twins',
    'trickster',
    'nemesis',
    'cenobite',
    'artist',
    'onryo',
    'dredge',
    'mastermind',
    'knight',
    'skullmerchant',
    'singularity',
    'xenomorph',
    'goodguy',
    'unknown'
]; // list of all available killers

const KILLER_PERKS = [
    'aNursesCalling',
    'agitation',
    'alienInstinct',
    'awakenedAwareness',
    'bamboozle',
    'barbecueAndChilli',
    'batteriesIncluded',
    'beastOfPrey',
    'bitterMurmur',
    'bloodEcho',
    'bloodWarden',
    'bloodhound',
    'brutalStrength',
    'callOfBrine',
    'corruptIntervention',
    'coulrophobia',
    'coupDeGr%3Fce',
    'cruelLimits',
    'darkDevotion',
    'darknessRevealed',
    'deadMansSwitch',
    'deadlock',
    'deathbound',
    'deerstalker',
    'discordance',
    'dissolution',
    'distressing',
    'dragonsGrip',
    'dyingLight',
    'enduring',
    'eruption',
    'fireUp',
    'forcedHesitation',
    'forcedPenance',
    'franklinsDemise',
    'friendsTilTheEnd',
    'furtiveChase',
    'gameAfoot',
    'gearhead',
    'geneticLimits',
    'grimEmbrace',
    'hexBloodFavour',
    'hexCrowdControl',
    'hexDevourHope',
    'hexFaceTheDarkness',
    'hexHauntedGround',
    'hexHuntressLullaby',
    'hexNoOneEscapesDeath',
    'hexPentimento',
    'hexPlaything',
    'hexRetribution',
    'hexRuin',
    'hexTheThirdSeal',
    'hexThrillOfTheHunt',
    'hexTwoCanPlay',
    'hexUndying',
    'hoarder',
    'hubris',
    'hysteria',
    'imAllEars',
    'infectiousFright',
    'insidious',
    'ironGrasp',
    'ironMaiden',
    'knockOut',
    'lethalPursuer',
    'leverage',
    'lightborn',
    'machineLearning',
    'madGrit',
    'makeYourChoice',
    'mercilessStorm',
    'mindbreaker',
    'monitorAndAbuse',
    'nemesis',
    'noWayOut',
    'nowhereToHide',
    'oppression',
    'overcharge',
    'overwhelmingPresence',
    'playWithYourFood',
    'popGoesTheWeasel',
    'predator',
    'rancor',
    'rapidBrutality',
    'rememberMe',
    'saveTheBestForLast',
    'scourgeHookFloodsOfRage',
    'scourgeHookGiftOfPain',
    'scourgeHookHangmansTrick',
    'scourgeHookMonstrousShrine',
    'scourgeHookPainResonance',
    'septicTouch',
    'shadowbord',
    'shatteredHope',
    'sloopyButcher',
    'spiesFromTheShadows',
    'spiritFury',
    'starstruck',
    'stridor',
    'superiorAnatomy',
    'surge',
    'surveillance',
    'terminus',
    'territorialImperative',
    'thanatophobia',
    'thrillingTremors',
    'thwack',
    'tinkerer',
    'trailOfTorment',
    'ultimateWeapon',
    'unbound',
    'undone',
    'unforeseen',
    'unnervingPresence',
    'unrelenting',
    'whispers',
    'zanshinTactics'
]; // list of all killers perks

const SURVIVOR_PERKS = [
    'aceInTheHole',
    'adrenaline',
    'aftercare',
    'alert',
    'anyMeansNecessary',
    'appraisal',
    'autodidact',
    'babysitter',
    'backgroundPlayer',
    'balancedLanding',
    'betterThanNew',
    'betterTogether',
    'biteTheBullet',
    'blastMine',
    'bloodPact',
    'bloodRush',
    'boilOver',
    'bond',
    'boonCircleOfHealing',
    'boonDarkTheory',
    'boonExponential',
    'boonIllumination',
    'boonShadowStep',
    'borrowedTime',
    'botanyKnowledge',
    'breakdown',
    'breakout',
    'buckleUp',
    'builtToLast',
    'calmSpirit',
    'camaraderie',
    'ChampionOfLight',
    'chemicalTrap',
    'clairvoyance',
    'correctiveAction',
    'counterforce',
    'cutLoose',
    'danceWithMe',
    'darkSense',
    'deadHard',
    'deadline',
    'deception',
    'decisiveStrike',
    'dejaVu',
    'deliverance',
    'desperateMeasures',
    'detectivesHunch',
    'distortion',
    'diversion',
    'dramaturgy',
    'empathicConnection',
    'empathy',
    'fastTrack',
    'fixated',
    'flashbang',
    'flip-Flop',
    'fogwise',
    'forThePeople',
    'friendlyCompetition',
    'headOn',
    'hope',
    'hyperfocus',
    'innerFocus',
    'innerStrength',
    'invocationWeavingSpiders',
    'ironWill',
    'kindred',
    'leader',
    'leftBehind',
    'light-Footed',
    'lightweight',
    'lithe',
    'lowProfile',
    'luckyBreak',
    'luckyStar',
    'madeForThis',
    'mettleOfMan',
    'noMither',
    'noOneLeftBehind',
    'objectOfObsession',
    'offTheRecord',
    'open-Handed',
    'overcome',
    'overzealous',
    'parentalGuidance',
    'pharmacy',
    'plotTwist',
    'plunderersInstinct',
    'poised',
    'potentialEnergy',
    'powerStruggle',
    'premonition',
    'proveThyself',
    'quickGambit',
    'reactiveHealing',
    'reassurance',
    'redHerring',
    'repressedAlliance',
    'residualManifest',
    'resilience',
    'resurgence',
    'rookieSpirit',
    'saboteur',
    'scavenger',
    'scenePartner',
    'secondWind',
    'self-Care',
    'self-Preservation',
    'slipperyMeat',
    'smallGame',
    'smashHit',
    'soleSurvivor',
    'solidarity',
    'soulGuard',
    'spineChill',
    'sprintBurst',
    'stakeOut',
    'streetwise',
    'strengthInShadows',
    'teamworkCollectiveStealth',
    'teamworkPowerOfTwo',
    'technician',
    'tenacity',
    'thisIsNotHappening',
    'troubleshooter',
    'unbreakable',
    'upTheAnte',
    'urbanEvasion',
    'vigil',
    'visionary',
    'wakeUp',
    'wellMakeIt',
    'wereGonnaLiveForever',
    'wicked',
    'windowsOfOpportunity',
    'wiretap'
]; // list of all survivor perks

const RARE_PERKS = [];

const KILLER_POWERS = {
    'trapper': {
        image: 'trap',
        addons: [
            { name: 'Bear Oil', image: 'bearOil', rarity: 'common', frenchName: 'Huile d\'ours' },
            { name: 'Makeshift Wrap', image: 'makeshiftWrap', rarity: 'common', frenchName: 'Écharpe Improvisée' },
            { name: 'Padded Jaws', image: 'paddedJaws', rarity: 'common', frenchName: 'Mâchoires Molletonnées' },
            { name: 'Trapper Gloves', image: 'trapperGloves', rarity: 'common', frenchName: 'Gants du Piégeur' },
            { name: '4-Coil Sprint Kit', image: '4-coilSpringKit', rarity: 'uncommon', frenchName: 'Kit à Quatre Ressorts' },
            { name: 'Coffee Grounds', image: 'coffeeGrounds', rarity: 'uncommon', frenchName: 'Café Moulu' },
            { name: 'Lengthened Jaws', image: 'lengthenedJaws', rarity: 'uncommon', frenchName: 'Mâchoires Allongées' },
            { name: 'Serrated Jaws', image: 'serratedJaws', rarity: 'uncommon', frenchName: 'Mâchoires Dentelées' },
            { name: 'Wax Brick', image: 'waxBrick', rarity: 'uncommon', frenchName: 'Brique de Cire' },
            { name: 'Fastening Tools', image: 'fasteningTools', rarity: 'rare', frenchName: 'Outils d\'Assemblage' },
            { name: 'Rusted Jaws', image: 'rustedJaws', rarity: 'rare', frenchName: 'Mâchoires Rouillées' },
            { name: 'Secondary Coil', image: 'secondaryCoil', rarity: 'rare', frenchName: 'Ressort Secondaire' },
            { name: 'Tar Bottle', image: 'tarBottle', rarity: 'rare', frenchName: 'Bouteille de Goudron' },
            { name: 'Trapper Bag', image: 'trapperBag', rarity: 'rare', frenchName: 'Sacoche du Piégeur' },
            { name: 'Honing Stone', image: 'honingStone', rarity: 'veryrare', frenchName: 'Pierre à Aiguiser' },
            { name: 'Oily Coil', image: 'oilyCoil', rarity: 'veryrare', frenchName: 'Ressort Huilé' },
            { name: 'Tension Spring', image: 'tensionSpring', rarity: 'veryrare', frenchName: 'Ressort à Tension' },
            { name: 'Trapper Sack', image: 'trapperSack', rarity: 'veryrare', frenchName: 'Sac du Piégeur' },
            { name: 'Bloody Coil', image: 'bloodyCoil', rarity: 'ultra', frenchName: 'Ressort Sanglant' },
            { name: 'Iridescent Stone', image: 'iridescentStone', rarity: 'ultra', frenchName: 'Pierre Irisée' }
        ]
    },
    'wraith': {
        image: 'bell',
        addons: [
            { name: '"The Beast" - Soot', image: 'theBeast-Soot', rarity: 'common', frenchName: '"La Bête" - Suie' },
            { name: '"The Ghost" - Soot', image: 'theGhost-Soot', rarity: 'common', frenchName: '"Ghost Face" - Suie' },
            { name: '"The Hound" - Soot', image: 'theHound-Soot', rarity: 'common', frenchName: '"Le Molosse" - Suie' },
            { name: '"The Serpent" - Soot', image: 'theSerpent-Soot', rarity: 'common', frenchName: '"Le Serpent" - Suie' },
            { name: '"Blind Warrior" - Mud', image: 'blindWarrior-Mud', rarity: 'uncommon', frenchName: '"Guerrier Aveugle" - Boue' },
            { name: '"Blink" - Mud', image: 'blink-Mud', rarity: 'uncommon', frenchName: '"Évanouissement" - Boue' },
            { name: '"Swift Hunt" - Mud', image: 'swiftHunt-Mud', rarity: 'uncommon', frenchName: '"Chasse Preste" - Boue' },
            { name: '"Windstorm" - Mud', image: 'windstorm-Mud', rarity: 'uncommon', frenchName: '"Tempête" - Boue' },
            { name: 'Bone Clapper', image: 'boneClapper', rarity: 'uncommon', frenchName: 'Battant en Os' },
            { name: '"Blind Warrior" - White', image: 'blindWarrior-White', rarity: 'rare', frenchName: '"Guerrier Aveugle" - Blanc' },
            { name: '"Blink" - White', image: 'blink-White', rarity: 'rare', frenchName: '"Évanouissement" - Blanc' },
            { name: '"Shadow Dance" - White', image: 'shadowDance-White', rarity: 'rare', frenchName: '"Danse de l\'Ombre" - Blanc' },
            { name: '"Swift Hunt" - White', image: 'swiftHunt-White', rarity: 'rare', frenchName: '"Chasse Preste" - Blanc' },
            { name: '"Windstorm" - White', image: 'windstorm-White', rarity: 'rare', frenchName: '"Tempête" - Blanc' },
            { name: '"All Seeing" - Blood', image: 'allSeeing-Blood', rarity: 'veryrare', frenchName: '"Clairvoyant" - Sang' },
            { name: '"Shadow Dance" - Blood', image: 'shadowDance-Blood', rarity: 'veryrare', frenchName: '"Danse de l\'Ombre" - Sang' },
            { name: '"Swift Hunt" - Blood', image: 'swiftHunt-Blood', rarity: 'veryrare', frenchName: '"Chasse Preste" - Sang' },
            { name: '"Windstorm" - Blood', image: 'windstorm-Blood', rarity: 'veryrare', frenchName: '"Tempête" - Sang' },
            { name: '"All Seeing" - Spirit', image: 'allSeeing-Spirit', rarity: 'ultra', frenchName: '"Clairvoyant" - Esprit' },
            { name: 'Coxcombed Clapper', image: 'coxcombedClapper', rarity: 'ultra', frenchName: 'Battant Encordé' }
        ]
    },
    'hillbilly': {
        image: 'chainsaw',
        addons: [
            { name: 'Counterweight', image: 'counterweight', rarity: 'common', frenchName: 'Contrepoids' },
            { name: 'Cracked Primer Bulb', image: 'crackedPrimerBulb', rarity: 'common', frenchName: 'Bulbe d\'Amorce Fissuré' },
            { name: 'Dad\'s Boots', image: 'dadsBoots', rarity: 'common', frenchName: 'Bottes de Papa' },
            { name: 'Steel Toe Boots', image: 'steelToeBoots', rarity: 'common', frenchName: 'Bottes à Embout d\'Acier' },
            { name: 'Clogged Intake', image: 'cloggedIntake', rarity: 'uncommon', frenchName: 'Entrée d\'Air Bouchée' },
            { name: 'Greased Throttle', image: 'greasedThrottle', rarity: 'uncommon', frenchName: 'Commande des Gaz Graissée' },
            { name: 'Off-Brand Motor Oil', image: 'off-BrandMotorOil', rarity: 'uncommon', frenchName: 'Huile Moteur Bon Marché' },
            { name: 'Spiked Boots', image: 'spikedBoots', rarity: 'uncommon', frenchName: 'Bottes à Pointes' },
            { name: 'Thermal Casing', image: 'thermalCasing', rarity: 'uncommon', frenchName: 'Revêtement Thermique' },
            { name: 'Begrimed Chains', image: 'begrimedChains', rarity: 'rare', frenchName: 'Chaînes Souillées' },
            { name: 'Low Kickback Chains', image: 'lowKickbackChains', rarity: 'rare', frenchName: 'Chaînes à Faible Recul' },
            { name: 'Ragged Engine', image: 'raggedEngine', rarity: 'rare', frenchName: 'Moteur Irrégulier' },
            { name: 'The Thompsons\' Mix', image: 'theThompsonsMix', rarity: 'rare', frenchName: 'Le Mélange des Thompson' },
            { name: 'Apex Muffler', image: 'apexMuffler', rarity: 'veryrare', frenchName: 'Silencieux de Pointe' },
            { name: 'Flithy Slippers', image: 'flithySlippers', rarity: 'veryrare', frenchName: 'Pantoufles Sales' },
            { name: 'High-Speed Idler Screw', image: 'high-SpeedIdlerScrew', rarity: 'veryrare', frenchName: 'Vis de Tendeur de Haut Régime' },
            { name: 'LoPro Chains', image: 'loProChains', rarity: 'veryrare', frenchName: 'Tronçonneuse Lo Pro' },
            { name: 'Iridescent Engravings', image: 'iridescentEngravings', rarity: 'ultra', frenchName: 'Gravures Irisées' },
            { name: 'Tuned Carburettor', image: 'tunedCarburettor', rarity: 'ultra', frenchName: 'Carburateur Réglé' }
        ]
    },
    'nurse': {
        image: 'breath',
        addons: [
            { name: 'Metal Spoon', image: 'metalSpoon', rarity: 'common', frenchName: 'Cuillère en Métal' },
            { name: 'Plaid Flannel', image: 'plaidFlannel', rarity: 'common', frenchName: 'Morceau de Plaid' },
            { name: 'White Nit Comb', image: 'whiteNitComb', rarity: 'common', frenchName: 'Peigne à Lentes Blanc' },
            { name: 'Wooden Horse', image: 'woodenHorse', rarity: 'common', frenchName: 'Cheval de Bois' },
            { name: 'Bad Man Keepsake', image: 'badManKeepsake', rarity: 'uncommon', frenchName: 'Souvenir du Méchant' },
            { name: 'Catatonic Boy\'s Treasure', image: 'catatonicBoysTreasure', rarity: 'uncommon', frenchName: 'Trésor d\'un Garçon Catatonique' },
            { name: 'Dark Cincture', image: 'darkCincture', rarity: 'uncommon', frenchName: 'Ceinture Obscure' },
            { name: 'Dull Bracelet', image: 'dullBracelet', rarity: 'uncommon', frenchName: 'Bracelet Terne' },
            { name: 'Pocket Watch', image: 'pocketWatch', rarity: 'uncommon', frenchName: 'Montre à Gousset' },
            { name: 'Anxious Gasp', image: 'anxiousGasp', rarity: 'rare', frenchName: 'Cri d\'Anxiété' },
            { name: 'Ataxic Respiration', image: 'ataxicRespiration', rarity: 'rare', frenchName: 'Respiration Ataxique' },
            { name: 'Fragile Wheeze', image: 'fragileWheeze', rarity: 'rare', frenchName: 'Respiration Difficile' },
            { name: 'Heavy Panting', image: 'heavyPanting', rarity: 'rare', frenchName: 'Halètement Intense' },
            { name: 'Spasmodic Breath', image: 'spasmodicBreath', rarity: 'rare', frenchName: 'Respiration Spasmodique' },
            { name: '"Bad Man\'s" Last Breath', image: 'badMansLastBreath', rarity: 'veryrare', frenchName: 'Dernier Souffle du "Méchant"' },
            { name: 'Campbell\'s Last Breath', image: 'campbellsLastBreath', rarity: 'veryrare', frenchName: 'Dernier Souffle de Campbell' },
            { name: 'Jenner\'s Last Breath', image: 'jennersLastBreath', rarity: 'veryrare', frenchName: 'Dernier Souffle de Jenner' },
            { name: 'Kavanagh\'s Last Breath', image: 'kavanaghsLastBreath', rarity: 'veryrare', frenchName: 'Dernier Souffle de Kavanagh' },
            { name: 'Matchbox', image: 'matchbox', rarity: 'ultra', frenchName: 'Boîte d\'Allumettes' },
            { name: 'Torn Bookmark', image: 'tornBookmark', rarity: 'ultra', frenchName: 'Signet Déchiré' }
        ]
    },
    'shape': {
        image: 'stalker1',
        addons: [
            { name: 'Blond Hair', image: 'blondHair', rarity: 'common', frenchName: 'Cheveux Blonds' },
            { name: 'Boyfriend\'s Memo', image: 'boyfriendsMemo', rarity: 'common', frenchName: 'Note du Petit Ami' },
            { name: 'Memorial Flower', image: 'memorialFlower', rarity: 'common', frenchName: 'Fleur Commémorative' },
            { name: 'Tacky Earrings', image: 'tackyEarrings', rarity: 'common', frenchName: 'Boucles d\'Oreilles Kitsch' },
            { name: 'Dead Rabbit', image: 'deadRabbit', rarity: 'uncommon', frenchName: 'Lapin Mort' },
            { name: 'Glass Fragment', image: 'glassFragment', rarity: 'uncommon', frenchName: 'Fragment de Verre' },
            { name: 'Hair Brush', image: 'hairBrush', rarity: 'uncommon', frenchName: 'Brosse à Cheveux' },
            { name: 'Jewellery', image: 'jewellery', rarity: 'uncommon', frenchName: 'Bijoux' },
            { name: 'Reflective Fragment', image: 'reflectiveFragment', rarity: 'uncommon', frenchName: 'Fragment Réfléchissant' },
            { name: 'Hair Bow', image: 'hairBow', rarity: 'rare', frenchName: 'Ruban' },
            { name: 'J. Myers Memorial', image: 'jMyersMemorial', rarity: 'rare', frenchName: 'Mémorial de J. Myers' },
            { name: 'Jewellery Box', image: 'jewelleryBox', rarity: 'rare', frenchName: 'Boite à Bijoux' },
            { name: 'Judith\'s Journal', image: 'judithsJournal', rarity: 'rare', frenchName: 'Journal de Judith' },
            { name: 'Mirror Shard', image: 'mirrorShard', rarity: 'rare', frenchName: 'Morceau de Miroir' },
            { name: 'Lock of Hair', image: 'lockOfHair', rarity: 'veryrare', frenchName: 'Mèche de Cheveux' },
            { name: 'Scratched Mirror', image: 'scratchedMirror', rarity: 'veryRare', frenchName: 'Miroir Rayé' },
            { name: 'Tombstone Piece', image: 'tombstonePiece', rarity: 'veryRare', frenchName: 'Morceau de Pierre Tombale' },
            { name: 'Vanity Mirror', image: 'vanityMirror', rarity: 'veryRare', frenchName: 'Miroir' },
            { name: 'Fragrant Tuft of Hair', image: 'fragrandTuftOfHair', rarity: 'ultra', frenchName: 'Touffe de Cheveux Parfumée' },
            { name: 'Judith\'s Tombstone', image: 'judithsTombstone', rarity: 'ultra', frenchName: 'Pierre Tombale de Judith' }
        ]
    },
    'hag': {
        image: 'blackenedCatalyst',
        addons: [
            { name: 'Bog Water', image: 'bogWater', rarity: 'common', frenchName: 'Eau du Bourbier' },
            { name: 'Dead Fly Mud', image: 'deadFlyMud', rarity: 'common', frenchName: 'Boue et Mouches Mortes' },
            { name: 'Powdered Eggshell', image: 'powderedEggshell', rarity: 'common', frenchName: 'Coquille d\'Oeuf Pulvérisée' },
            { name: 'Rope Necklet', image: 'ropeNecklet', rarity: 'common', frenchName: 'Collier en Corde' },
            { name: 'Bloodied Water', image: 'bloodiedWater', rarity: 'uncommon', frenchName: 'Eau Sanglante' },
            { name: 'Cypress Necklet', image: 'cypressNecklet', rarity: 'uncommon', frenchName: 'Collier en Cyprès' },
            { name: 'Dragonfly Wings', image: 'dragonflyWings', rarity: 'uncommon', frenchName: 'Ailes de Libellule' },
            { name: 'Half Eggshell', image: 'halfEggshell', rarity: 'uncommon', frenchName: 'Moitié de Coquille d\'Oeuf' },
            { name: 'Pussy Willow Catkins', image: 'pussyWillowCatkins', rarity: 'uncommon', frenchName: 'Chatons de Saulte' },
            { name: 'Bloodied Mud', image: 'bloodiedMud', rarity: 'rare', frenchName: 'Boue Sanglante' },
            { name: 'Cracked Turtle Egg', image: 'crackedTurtleEgg', rarity: 'rare', frenchName: 'Oeuf de Tortue Fêlé' },
            { name: 'Dried Cicada', image: 'driedCicada', rarity: 'rare', frenchName: 'Cigale Séchée' },
            { name: 'Swamp Orchid Necklet', image: 'swampOrchidNecklet', rarity: 'rare', frenchName: 'Collier d\'Orchidées des Marais' },
            { name: 'Willow Wreath', image: 'willowWreath', rarity: 'rare', frenchName: 'Couronne en Saule' },
            { name: 'Disfigured Ear', image: 'disfiguredEar', rarity: 'veryrare', frenchName: 'Oreille Déformée' },
            { name: 'Grandma\'s Heart', image: 'grandmasHeart', rarity: 'veryrare', frenchName: 'Coeur de Grand-Mère' },
            { name: 'Rusty Shackles', image: 'rustyshackles', rarity: 'veryrare', frenchName: 'Chaînes Rouillées' },
            { name: 'Scarred Hand', image: 'scarredHand', rarity: 'veryrare', frenchName: 'Main Balafrée' },
            { name: 'Mint Rag', image: 'mintRag', rarity: 'ultra', frenchName: 'Lambeau de Tissu Comme Neuf' },
            { name: 'Waterlogged Shoe', image: 'waterloggedShoe', rarity: 'ultra', frenchName: 'Chaussure Détrempée' }
        ]
    },
    'doctor': {
        image: 'cartersSpark',
        addons: [
            { name: '"Calm" - Class I', image: 'calm-ClassI', rarity: 'common', frenchName: '"Calme" - Cours I' },
            { name: '"Order" - Class I', image: 'order-ClassI', rarity: 'common', frenchName: '"Ordre" - Cours I' },
            { name: 'Maple Knight', image: 'mapleKnight', rarity: 'common', frenchName: 'Cavalier Érable' },
            { name: 'Mouldy Electrode', image: 'mouldyElectrode', rarity: 'common', frenchName: 'Vieille Électrode' },
            { name: '"Calm" - Class II', image: 'calm-ClassII', rarity: 'uncommon', frenchName: '"Calme" - Cours II' },
            { name: '"Discipline" - Class II', image: 'discipline-ClassII', rarity: 'uncommon', frenchName: '"Discipline" - Cours II' },
            { name: '"Order" - Class II', image: 'order-ClassII', rarity: 'uncommon', frenchName: '"Ordre" - Cours II' },
            { name: '"Restraint" - Class II', image: 'restraint-ClassII', rarity: 'uncommon', frenchName: '"Contrainte" - Cours II' },
            { name: 'Polished Electrode', image: 'polishedElectrode', rarity: 'uncommon', frenchName: 'Électrode Brillante' },
            { name: '"Discipline" - Class III', image: 'discipline-ClassIII', rarity: 'rare', frenchName: '"Discipline" - Cours III' },
            { name: '"Restraint" - Class III', image: 'restraint-ClassIII', rarity: 'rare', frenchName: '"Contrainte" - Cours III' },
            { name: 'High Stimulus Electrode', image: 'highStimulusElectrode', rarity: 'rare', frenchName: 'Électrode à Stimulation Élevée' },
            { name: 'Interview Tape', image: 'interviewTape', rarity: 'rare', frenchName: 'Cassette d\'Entretient'},
            { name: 'Scrapped Tape', image: 'scrappedTape', rarity: 'rare', frenchName: 'Cassette Abîmée' },
            { name: '"Calm" - Carter\'s Notes', image: 'calm-CartersNotes', rarity: 'veryrare', frenchName: '"Calme" - Notes de Carter' },
            { name: '"Discipline" - Carter\'s Notes', image: 'discipline-CartersNotes', rarity: 'veryrare', frenchName: '"Discipline" - Notes de Carter' },
            { name: '"Order" - Carter\'s Notes', image: 'order-CartersNotes', rarity: 'veryrare', frenchName: '"Ordre" - Notes de Carter' },
            { name: '"Restraint" - Carter\'s Notes', image: 'restraint-CartersNotes', rarity: 'veryrare', frenchName: '"Contrainte" - Notes de Carter' },
            { name: 'Iridescent King', image: 'iridescentKing', rarity: 'ultra', frenchName: 'Roi Irisé' },
            { name: 'Iridescent Queen', image: 'iridescentQueen', rarity: 'ultra', frenchName: 'Reine Irisée' }
        ]
    },
    'huntress': {
        image: 'huntingHatchets',
        addons: [
            { name: 'Amanita Toxin', image: 'amanitaToxin', rarity: 'common', frenchName: 'Toxine d\'Amanite' },
            { name: 'Bandaged Haft', image: 'bandagedHaft', rarity: 'common', frenchName: 'Manche Bandé' },
            { name: 'Coarse Stone', image: 'coarseStone', rarity: 'common', frenchName: 'Pierre Grossière' },
            { name: 'Yellowed Cloth', image: 'yellowedCloth', rarity: 'common', frenchName: 'Tissu Jaune' },
            { name: 'Leather Loop', image: 'leatherLoop', rarity: 'uncommon', frenchName: 'Boucle en Cuir' },
            { name: 'Manna Grass Braid', image: 'mannaGrassBraid', rarity: 'uncommon', frenchName: 'Tresse de Glycérie' },
            { name: 'Oak Haft', image: 'oakHaft', rarity: 'uncommon', frenchName: 'Manche en Chêne' },
            { name: 'Shiny Pin', image: 'shinyPin', rarity: 'uncommon', frenchName: 'Épingle Brillante' },
            { name: 'Weighted Head', image: 'weightedHead', rarity: 'uncommon', frenchName: 'Tête Lestée' },
            { name: 'Deerskin Gloves', image: 'deerskinGloves', rarity: 'rare', frenchName: 'Gants en Peau de Daim' },
            { name: 'Flower Babushka', image: 'flowerBabushka', rarity: 'rare', frenchName: 'Poupée Russe à Fleurs' },
            { name: 'Rose Root', image: 'roseRoot', rarity: 'rare', frenchName: 'Racine de Rose' },
            { name: 'Rusty Head', image: 'rustyHead', rarity: 'rare', frenchName: 'Tête Rouillée' },
            { name: 'Venomous Concoction', image: 'venomousConcoction', rarity: 'rare', frenchName: 'Concoction Vénéneuse' },
            { name: 'Begrimed Head', image: 'begrimedHead', rarity: 'veryrare', frenchName: 'Tête Souillée' },
            { name: 'Glowing Concoction', image: 'glowingConcoction', rarity: 'veryrare', frenchName: 'Concoction Luisante' },
            { name: 'Infantry Belt', image: 'infantryBelt', rarity: 'veryrare', frenchName: 'Ceinture d\'Infanterie' },
            { name: 'Wooden Fox', image: 'woodenFox', rarity: 'veryrare', frenchName: 'Renard de Bois' },
            { name: 'Iridescent Head', image: 'iridescentHead', rarity: 'ultra', frenchName: 'Tête Irisée' },
            { name: 'Soldier\'s Puttee', image: 'soldiersPuttee', rarity: 'ultra', frenchName: 'Bande Molletière de Soldat' }
        ]
    },
    'cannibal': {
        image: 'bubbasChainsaw',
        addons: [
            { name: 'Chainsaw File', image: 'chainsawFile', rarity: 'common', frenchName: 'Aiguiseur de Chaîne' },
            { name: 'Spark Plug', image: 'sparkPlug', rarity: 'common', frenchName: 'Bougie d\'Allumage' },
            { name: 'Speed Limiter', image: 'speedLimiter', rarity: 'common', frenchName: 'Limiteur de Vitesse' },
            { name: 'Vegetable Oil', image: 'vegetableOil', rarity: 'common', frenchName: 'Huile Végétale' },
            { name: 'Chilli', image: 'chilli', rarity: 'uncommon', frenchName: 'Chili' },
            { name: 'Homemade Muffler', image: 'homemadeMuffler', rarity: 'uncommon', frenchName: 'Silencieux Fait Maison' },
            { name: 'Knife Scratches', image: 'knifeScratches', rarity: 'uncommon', frenchName: 'Griffures de Couteau' },
            { name: 'Long Guide Bar', image: 'longGuideBar', rarity: 'uncommon', frenchName: 'Guide Allongé' },
            { name: 'Primer Bulb', image: 'primerBulb', rarity: 'uncommon', frenchName: 'Poire d\'Amorçage' },
            { name: 'Begrimed Chains', image: 'begrimedChains', rarity: 'rare', frenchName: 'Chaînes Souillées' },
            { name: 'Grisly Chains', image: 'grislyChains', rarity: 'rare', frenchName: 'Chaîne Macabre' },
            { name: 'Shop Lubricant', image: 'shopLubricant', rarity: 'rare', frenchName: 'Lubrifiant d\'Atelier' },
            { name: 'The Beast\'s Marks', image: 'theBeastsMarks', rarity: 'rare', frenchName: 'Les Marques de la Bête' },
            { name: 'The Grease', image: 'theGrease', rarity: 'rare', frenchName: 'La Graisse' },
            { name: 'Award-winning Chilli', image: 'award-winningChilli', rarity: 'veryrare', frenchName: 'Chili Primé' },
            { name: 'Depth Gauge Rake', image: 'depthGaugeRake', rarity: 'veryrare', frenchName: 'Allonge de Profondeur' },
            { name: 'Light Chassis', image: 'lightChassis', rarity: 'veryrare', frenchName: 'Châssis Léger' },
            { name: 'Rusted Chains', image: 'rustedChains', rarity: 'veryrare', frenchName: 'Chaîne Rouillée' },
            { name: 'Carburettor Tuning Guide', image: 'carburettorTuningGuide', rarity: 'ultra', frenchName: 'Guide de Réglage de Carburateur' },
            { name: 'Iridescent Flesh', image: 'iridescentFlesh', rarity: 'ultra', frenchName: 'Chair Irisée' }
        ]
    },
    'nightmare': {
        image: 'dreamDemon',
        addons: [
            { name: 'Garden Rake', image: 'gardenRake', rarity: 'common', frenchName: 'Râteau' },
            { name: 'Kid\'s Drawing', image: 'kidsDrawing', rarity: 'common', frenchName: 'Dessin d\'Enfant' },
            { name: 'Sheep Block', image: 'sheepBlock', rarity: 'common', frenchName: 'Bloc Mouton' },
            { name: 'Wool Shirt', image: 'woolShirt', rarity: 'common', frenchName: 'Maillot en Laine' },
            { name: 'Cat Block', image: 'catBlock', rarity: 'uncommon', frenchName: 'Bloc Chat' },
            { name: 'Green Dress', image: 'greenDress', rarity: 'uncommon', frenchName: 'Robe Verte' },
            { name: 'Nancy\'s Sketch', image: 'nancysSketch', rarity: 'uncommon', frenchName: 'Croquis de Nancy' },
            { name: 'Outdoor Rope', image: 'outdoorRope', rarity: 'uncommon', frenchName: 'Corde de Randonnée' },
            { name: 'Prototype Claws', image: 'prototypeClaws', rarity: 'uncommon', frenchName: 'Prototype de Griffes' },
            { name: 'Blue Dress', image: 'blueDress', rarity: 'rare', frenchName: 'Robe Bleue' },
            { name: 'Jump Rope', image: 'jumpRope', rarity: 'rare', frenchName: 'Corde à Sauter' },
            { name: 'Nancy\'s Masterpiece', image: 'NancysMasterpiece', rarity: 'rare', frenchName: 'Chef-d\'Oeuvre de Nancy' },
            { name: 'Paint Thinner', image: 'paintThinner', rarity: 'rare', frenchName: 'Diluant à Peinture' },
            { name: 'Unicorn Block', image: 'unicornBlock', rarity: 'rare', frenchName: 'Bloc Licorne' },
            { name: '"Z" Block', image: 'zBlock', rarity: 'veryrare', frenchName: 'Bloc "Z"' },
            { name: 'Class Photo', image: 'classPhoto', rarity: 'veryrare', frenchName: 'Photo de Classe' },
            { name: 'Pill Bottle', image: 'pillBottle', rarity: 'veryrare', frenchName: 'Flacon de Cachets' },
            { name: 'Swing Chains', image: 'swingChains', rarity: 'veryrare', frenchName: 'Chaînes de Balançoire' },
            { name: 'Black Box', image: 'blackBox', rarity: 'ultra', frenchName: 'Boîte Noire' },
            { name: 'Red Paint Brush', image: 'redPaintBrush', rarity: 'ultra', frenchName: 'Pinceau avec Peinture Rouge' }
        ]
    },
    'pig': {
        image: 'jigsawsBaptism',
        addons: [
            { name: 'Combat Straps', image: 'combatStraps', rarity: 'common', frenchName: 'Sangles de Combat' },
            { name: 'Interlocking Razor', image: 'interlockingRazor', rarity: 'common', frenchName: 'Rasoirs Enchevêtrés' },
            { name: 'John\'s Medical File', image: 'JohnsMedicalFile', rarity: 'common', frenchName: 'Dossier Médical de John' },
            { name: 'Shattered Syringe', image: 'shatteredSyringe', rarity: 'common', frenchName: 'Seringue Brisée' },
            { name: 'Face Mask', image: 'faceMask', rarity: 'uncommon', frenchName: 'Masque' },
            { name: 'Last Will', image: 'lastWill', rarity: 'uncommon', frenchName: 'Testament' },
            { name: 'Razor Wires', image: 'razorWires', rarity: 'uncommon', frenchName: 'Fil Barbelé' },
            { name: 'Utility Blades', image: 'utilityBlades', rarity: 'uncommon', frenchName: 'Lames de Cutter' },
            { name: 'Workshop Grease', image: 'workshopGrease', rarity: 'uncommon', frenchName: 'Lubrifiant' },
            { name: 'Bag of Gears', image: 'bagOfGears', rarity: 'rare', frenchName: 'Sac de Rouages' },
            { name: 'Jigsaw\'s Annotated Plan', image: 'jigsawsAnnotatedPlan', rarity: 'rare', frenchName: 'Croquis Annoté de Jigsaw' },
            { name: 'Rules Set No.2', image: 'rulesSetNo2', rarity: 'rare', frenchName: 'Ensemble de Règles N°2' },
            { name: 'Rusty Attachments', image: 'rustyAttachments', rarity: 'rare', frenchName: 'Dents Rouillées' },
            { name: 'Slow-Release Toxin', image: 'slow-ReleaseToxin', rarity: 'rare', frenchName: 'Toxine à Libération Lente' },
            { name: 'Amanda\'s Secret', image: 'amandasSecret', rarity: 'veryrare', frenchName: 'Secret d\'Amanda' },
            { name: 'Crate of Gears', image: 'crateOfGears', rarity: 'veryrare', frenchName: 'Caisse de Rouages' },
            { name: 'Jigsaw\'s Sketch', image: 'jigsawsSketch', rarity: 'veryrare', frenchName: 'Croquis de Jigsaw' },
            { name: 'Tampered Timer', image: 'tamperedTimer', rarity: 'veryrare', frenchName: 'Minuteur Trafiqué' },
            { name: 'Amanda\'s Letter', image: 'amandasLetter', rarity: 'ultra', frenchName: 'Lettre à Amanda' },
            { name: 'Video Tape', image: 'videoTape', rarity: 'ultra', frenchName: 'Cassette Vidéo' }
        ]
    },
    'clown': {
        image: 'gasBomb',
        addons: [
            { name: 'Fingerless Parade Gloves', image: 'fingerlessParadeGloves', rarity: 'common', frenchName: 'Mitaines de Parade' },
            { name: 'Party Bottle', image: 'partyBottle', rarity: 'common', frenchName: 'Bouteille de Fête' },
            { name: 'Robin Feather', image: 'robinFeather', rarity: 'common', frenchName: 'Plume de Rouge-Gorge' },
            { name: 'VHS Porn', image: 'vhsPorn', rarity: 'common', frenchName: 'VHS Porn' },
            { name: 'Kerosene Can', image: 'keroseneCan', rarity: 'uncommon', frenchName: 'Bidon de Kérosène' },
            { name: 'Solvent Jug', image: 'solventJug', rarity: 'uncommon', frenchName: 'Bidon de Solvant' },
            { name: 'Starling Feather', image: 'starlingFeather', rarity: 'uncommon', frenchName: 'Plume d\'Étourneau' },
            { name: 'Sticky Soda Bottle', image: 'stickySodaBottle', rarity: 'uncommon', frenchName: 'Bouteille de Soda Collante' },
            { name: 'Thick Cork Stopper', image: 'thickCorkStopper', rarity: 'uncommon', frenchName: 'Bouchon Épais' },
            { name: 'Bottle of Chloroform', image: 'bottleOfChloroform', rarity: 'rare', frenchName: 'Bouteille de Chloroforme' },
            { name: 'Flask of Bleach', image: 'flaskOfBleach', rarity: 'rare', frenchName: 'Flacon de Détergent' },
            { name: 'Smelly Inner Soles', image: 'smellyInnerSoles', rarity: 'rare', frenchName: 'Semelles Intérieures Puantes' },
            { name: 'Spirit of Hartshorn', image: 'spiritOfHartshorn', rarity: 'rare', frenchName: 'Esprit de Hartshorn' },
            { name: 'Sulphuric Acid Vial', image: 'sulphuricAcidVial', rarity: 'rare', frenchName: 'Flacon d\'Acide Sulfurique' },
            { name: 'Cheap Gin Bottle', image: 'cheapGinBottle', rarity: 'veryrare', frenchName: 'Bouteille de Gin Bon Marché' },
            { name: 'Cigar Box', image: 'cigarBox', rarity: 'veryrare', frenchName: 'Boîte à Cigares' },
            { name: 'Ether 15 Vol%', image: 'ether15Vol%', rarity: 'veryrare', frenchName: 'Éther à 15 % du Volume' },
            { name: 'Garish Make-Up Kit', image: 'garishMake-UpKit', rarity: 'veryrare', frenchName: 'Boîte à Maquillage Criard' },
            { name: 'Redhead\'s Pinkie Finger', image: 'redheadsPinkieFinger', rarity: 'ultra', frenchName: 'Petit Doigt de Personne Rousse' },
            { name: 'Tattoo\'s Middle Finger', image: 'tattoosMiddleFinger', rarity: 'ultra', frenchName: 'Majeur du Tatoué' }
        ]
    },
    'spirit': {
        image: 'yamaokasHaunting',
        addons: [
            { name: 'Gifted Bamboo Comb', image: 'giftedBambooComb', rarity: 'common', frenchName: 'Peigne en Bambou Offert' },
            { name: 'Origami Crane', image: 'origamiCrane', rarity: 'common', frenchName: 'Grue en Origami' },
            { name: 'Shiawase Amulet', image: 'shiawaseAmulet', rarity: 'common', frenchName: 'Amulette Porte-Bonheur' },
            { name: 'Zori', image: 'zori', rarity: 'common', frenchName: 'Zori' },
            { name: 'Juniper Bonsai', image: 'juniperBonsai', rarity: 'uncommon', frenchName: 'Bonsaï de Genévrier' },
            { name: 'Kalun Talisman', image: 'kalunTalisman', rarity: 'uncommon', frenchName: 'Talisman de Chance' },
            { name: 'Muddy Sports Day Cap', image: 'muddySportsDayCap', rarity: 'uncommon', frenchName: 'Casquette de Sport Boueuse' },
            { name: 'Rin\'s Broken Watch', image: 'rinsBrokenWatch', rarity: 'uncommon', frenchName: 'Montre Cassée de Rin' },
            { name: 'White Hair Ribbon', image: 'whiteHairRibbon', rarity: 'uncommon', frenchName: 'Ruban Blanc pour Cheveux' },
            { name: 'Katana Tsuba', image: 'katanaTsuba', rarity: 'rare', frenchName: 'Tsuba pour Katana' },
            { name: 'Mother\'s Glasses', image: 'mothersGlasses', rarity: 'rare', frenchName: 'Lunettes de Mère' },
            { name: 'Rusty Flute', image: 'rustyFlute', rarity: 'rare', frenchName: 'Flûte Rouillée' },
            { name: 'Senko Hanabi', image: 'senkoHanabi', rarity: 'rare', frenchName: 'Senko Hanabi' },
            { name: 'Uchiwa', image: 'uchiwa', rarity: 'rare', frenchName: 'Uchiwa' },
            { name: 'Dried Cherry Blossom', image: 'driedCherryBlossom', rarity: 'veryrare', frenchName: 'Fleur de Cerisier Séchée' },
            { name: 'Furin', image: 'furin', rarity: 'veryrare', frenchName: 'Furin' },
            { name: 'Wakizashi Saya', image: 'wakizashiSaya', rarity: 'veryrare', frenchName: 'Fourreau de Wakizashi' },
            { name: 'Yakuyoke Amulet', image: 'yakuyokeAmulet', rarity: 'veryrare', frenchName: 'Amulette Yakuyoke' },
            { name: 'Kintsugi Teacup', image: 'kintsugiTeacup', rarity: 'ultra', frenchName: 'Tasse à Thé Kintsugi' },
            { name: 'Mother-Daughter Ring', image: 'mother-DaughterRing', rarity: 'ultra', frenchName: 'Bage Mère-Fille' }
        ]
    },
    'legion': {
        image: 'feralFrenzy',
        addons: [
            { name: 'Friendship Bracelet', image: 'friendshipBracelet', rarity: 'common', frenchName: 'Bracelet d\'Amitié' },
            { name: 'Mischief List', image: 'mischiefList', rarity: 'common', frenchName: 'Liste de Méfaits' },
            { name: 'Scratched Ruler', image: 'scratchedRuler', rarity: 'common', frenchName: 'Règle Éraflée' },
            { name: 'Smiley Face Pin', image: 'smileyFacePin', rarity: 'common', frenchName: 'Badge Smiley' },
            { name: 'Defaced Smiley Pin', image: 'defacedSmiley', rarity: 'uncommon', frenchName: 'Badge Smiley Défiguré' },
            { name: 'Etched Ruler', image: 'etchedRuler', rarity: 'uncommon', frenchName: 'Règle Entaillée' },
            { name: 'Julie\'s Mix Tape', image: 'juliesMixTape', rarity: 'uncommon', frenchName: 'Cassette de Musique' },
            { name: 'Mural Sketch', image: 'muralSketch', rarity: 'uncommon', frenchName: 'Fresque' },
            { name: 'Never-Sleep Pills', image: 'never-SleepPills', rarity: 'uncommon', frenchName: 'Cachets Anti-Sommeil' },
            { name: 'Joey\'s Mix Tape', image: 'joeysMixTape', rarity: 'rare', frenchName: 'Cassette de Musique de Susie' },
            { name: 'Stolen Sketch Book', image: 'StolenSketchBook', rarity: 'rare', frenchName: 'Carnet à Dessin Volé' },
            { name: 'Stylish Sunglasses', image: 'stylishSunglasses', rarity: 'rare', frenchName: 'Lunettes de Soleil Stylées' },
            { name: 'BFFs', image: 'bffs', rarity: 'veryrare', frenchName: 'Amis pour la Vie' },
            { name: 'Flithy Blade', image: 'flithyBlade', rarity: 'veryrare', frenchName: 'Lame Dégoûtante' },
            { name: 'Frank\'s Mix Tape', image: 'franksMixTape', rarity: 'veryrare', frenchName: 'Cassette de Musique de Frank' },
            { name: 'Stab Wounds Study', image: 'stabWoundsStudy', rarity: 'veryrare', frenchName: 'Étude sur les Blessures par Arme Blanche' },
            { name: 'Fuming Mix Tape', image: 'fumingMixTape', rarity: 'ultra', frenchName: 'Cassette de Musique Fumante' },
            { name: 'Iridescent Button', image: 'iridescentButton', rarity: 'ultra', frenchName: 'Badge Irisé' }
        ]
    },
    'plague': {
        image: 'vilePurge',
        addons: [
            { name: 'Healing Salve', image: 'healingSalve', rarity: 'common', frenchName: 'Baume de Soins' },
            { name: 'Limestone Seal', image: 'limestoneSeal', rarity: 'common', frenchName: 'Sceau Calcaire' },
            { name: 'Olibanum Incense', image: 'olibanumIncense', rarity: 'common', frenchName: 'Olibanum' },
            { name: 'Prayer Tablet Fragment', image: 'prayerTabletFragment', rarity: 'common', frenchName: 'Fragment de Tablette de Prière' },
            { name: 'Blessed Apple', image: 'blessedApple', rarity: 'uncommon', frenchName: 'Pomme Bénie' },
            { name: 'Emetic Potion', image: 'emeticPotion', rarity: 'uncommon', frenchName: 'PotionVomitive' },
            { name: 'Haematite Seal', image: 'haematiteSeal', rarity: 'uncommon', frenchName: 'Sceau d\'Hématite' },
            { name: 'Potent Tincture', image: 'potentTincture', rarity: 'uncommon', frenchName: 'Teinture Forte' },
            { name: 'Prophylactic Amulet', image: 'prophylacticAmulet', rarity: 'uncommon', frenchName: 'Amulette Prophylactique' },
            { name: 'Ashen Apple', image: 'ashenApple', rarity: 'rare', frenchName: 'Pomme Grisâtre' },
            { name: 'Exorcism Amulet', image: 'exorcismAmulet', rarity: 'rare', frenchName: 'Amulette d\'Exorcisme' },
            { name: 'Incensed Ointment', image: 'incensedOintment', rarity: 'rare', frenchName: 'Onguent Odorant' },
            { name: 'Infected Emetic', image: 'infectedEmetic', rarity: 'rare', frenchName: 'Vomi Infecté' },
            { name: 'Rubbing Oil', image: 'rubbingOil', rarity: 'rare', frenchName: 'Huile de Massage' },
            { name: 'Devotee\'s Amulet', image: 'devoteesAmulet', rarity: 'veryrare', frenchName: 'Amulette de l\'Adepte' },
            { name: 'Severed Toe', image: 'severedToe', rarity: 'veryrare', frenchName: 'Orteil Tranché' },
            { name: 'Vile Emetic', image: 'vileEmetic', rarity: 'veryrare', frenchName: 'Vomitif Abominable' },
            { name: 'Worship Tablet', image: 'worshipTablet', rarity: 'veryrare', frenchName: 'Tablette d\'Adoration' },
            { name: 'Black Incense', image: 'blackIncense', rarity: 'ultra', frenchName: 'Encens Noir' },
            { name: 'Iridescent Seal', image: 'iridescentSeal', rarity: 'ultra', frenchName: 'Sceau Irisé' }
        ]
    },
    'ghostface': {
        image: 'nightShroud',
        addons: [
            { name: '"Philly"', image: 'philly', rarity: 'common', frenchName: '"Philly"' },
            { name: 'Cheap Cologne', image: 'cheapCologne', rarity: 'common', frenchName: 'Eau de Cologne Bon Marché' },
            { name: 'Headline Cut-Outs', image: 'headlineCut-Outs', rarity: 'common', frenchName: 'Coupures de Presse' },
            { name: 'Walleye\'s Matchbook', image: 'walleyesMatchbook', rarity: 'common', frenchName: 'Allumettes du Walleye' },
            { name: 'Cinch Straps', image: 'cinchStraps', rarity: 'uncommon', frenchName: 'Sangles' },
            { name: 'Marked Map', image: 'markedMap', rarity: 'uncommon', frenchName: 'Carte Marquée' },
            { name: 'Olsen\'s Address Book', image: 'olsensAddressBook', rarity: 'uncommon', frenchName: 'Carnet d\'Adresses d\'Olsen' },
            { name: 'Olsen\'s Journal', image: 'olsensJournal', rarity: 'uncommon', frenchName: 'Journal d\'Olsen' },
            { name: 'Telephoto Lens', image: 'telephotoLens', rarity: 'uncommon', frenchName: 'Téléobjectif' },
            { name: 'Chewed Pen', image: 'chewedPen', rarity: 'rare', frenchName: 'Stylo Mâchouillé' },
            { name: 'Knife Belt Clip', image: 'knifeBeltClip', rarity: 'rare', frenchName: 'Étui de Ceinture à Couteau' },
            { name: 'Lasting Perfume', image: 'lastingPerfume', rarity: 'rare', frenchName: 'Parfum Durable' },
            { name: 'Leather Knife Sheath', image: 'leatherKnifeSheath', rarity: 'rare', frenchName: 'Fourreau de Couteau en Cuir' },
            { name: 'Olsen\'s Wallet', image: 'olsensWallet', rarity: 'rare', frenchName: 'Porte-Feuille d\'Olsen' },
            { name: 'Driver\'s License', image: 'Permis de Conduire', rarity: 'veryrare', frenchName: 'Permis de Conduire' },
            { name: 'Drop-Leg Knife Sheath', image: 'drop-LegKnifeSheath', rarity: 'veryrare', frenchName: 'Fourreau de Couteau Fixe' },
            { name: 'Night Vision Monocular', image: 'nightVisionMonocular', rarity: 'veryrare', frenchName: 'Objectif de Vision Nocturne' },
            { name: 'Victim\'s Detailed Routine', image: 'victimsDetailedRoutine', rarity: 'veryrare', frenchName: 'Routine Détaillée de la Victime' },
            { name: '"Ghost Face Caught on Tape"', image: 'ghostFaceCaughtOnTape', rarity: 'ultra', frenchName: '"Ghost Face Surpris en Direct"' },
            { name: 'Outdoor Security Camera', image: 'outdoorSecurityCamera', rarity: 'ultra', frenchName: 'Caméra de Sécurité Extérieure' }
        ]
    },
    'demogorgon': {
        image: 'ofTheAbyss',
        addons: [
            { name: 'Black Heart', image: 'blackHeart', rarity: 'common', frenchName: 'Coeur Noir' },
            { name: 'Rat Liver', image: 'ratLiver', rarity: 'common', frenchName: 'Foie de Rat' },
            { name: 'Rat Tail', image: 'ratTail', rarity: 'common', frenchName: 'Queue de Rat' },
            { name: 'Rotten Pumpkin', image: 'rottenPumpkin', rarity: 'common', frenchName: 'Citrouille Pourrie' },
            { name: 'Barb\'s Glasses', image: 'barbsGlasses', rarity: 'uncommon', frenchName: 'Lunettes de Barb' },
            { name: 'Mews\' Guts', image: 'mewsGuts', rarity: 'uncommon', frenchName: 'Boyaux de Miaou' },
            { name: 'Rotten Green Tripe', image: 'rottenGreenTripe', rarity: 'uncommon', frenchName: 'Tripes Vertes Décomposées' },
            { name: 'Sticky Lining', image: 'stickyLining', rarity: 'uncommon', frenchName: 'Revêtement Gluant' },
            { name: 'Viscous Webbing', image: 'viscousWebbing', rarity: 'uncommon', frenchName: 'Toile Visqueuse' },
            { name: 'Brass Case Lighter', image: 'brassCaseLighter', rarity: 'rare', frenchName: 'Briquet en Cuivre' },
            { name: 'Deer Lung', image: 'deerLung', rarity: 'rare', frenchName: 'Poumon de Biche' },
            { name: 'Eleven\'s Soda', image: 'elevensSoda', rarity: 'rare', frenchName: 'Soda de Onze' },
            { name: 'Thorny Vines', image: 'thornyVines', rarity: 'rare', frenchName: 'Lianes Épineuses' },
            { name: 'Violet Waxcap', image: 'violetWaxcap', rarity: 'rare', frenchName: 'Bonnet Cireux Violet' },
            { name: 'Lifeguard Whistle', image: 'lifeguardWhistle', rarity: 'veryrare', frenchName: 'Sifflet de Maître-Nageur' },
            { name: 'Unknown Egg', image: 'unknownEgg', rarity: 'veryrare', frenchName: 'Oeuf Inconnu' },
            { name: 'Upside Down Resin', image: 'upsideDownResin', rarity: 'veryrare', frenchName: 'Résine Sens Dessus Dessous' },
            { name: 'Vermillon Webcap', image: 'vermillonWebcap', rarity: 'veryrare', frenchName: 'Petit Bonnet Vermillon' },
            { name: 'Leprose Lichen', image: 'leproseLichen', rarity: 'ultra', frenchName: 'Lichen Lépreux' },
            { name: 'Red Moss', image: 'redMoss', rarity: 'ultra', frenchName: 'Mousse Rouge' }
        ]
    },
    'oni': {
        image: 'yamaokasWrath',
        addons: [
            { name: 'Blackened Toenail', image: 'blackenedToenail', rarity: 'common', frenchName: 'Ongle de Pied Noirci' },
            { name: 'Cracked Sakazuki', image: 'crackedSakazuki', rarity: 'common', frenchName: 'Sakazuki Fêlée' },
            { name: 'Paper Lantern', image: 'paperLantern', rarity: 'common', frenchName: 'Lanterne en Papier' },
            { name: 'Rotting Rope', image: 'rottingRope', rarity: 'common', frenchName: 'Corde en Décomposition' },
            { name: 'Bloody Sash', image: 'bloodySash', rarity: 'uncommon', frenchName: 'Écharpe Sanglante' },
            { name: 'Child\'s Wooden Sword', image: 'childsWoodenSword', rarity: 'uncommon', frenchName: 'Épée de Bois d\'Enfant' },
            { name: 'Chipped Salhal', image: 'chippedSalhal', rarity: 'uncommon', frenchName: 'Salhal Ébréché' },
            { name: 'Ink Lion', image: 'inkLion', rarity: 'uncommon', frenchName: 'Lion à l\'Encre' },
            { name: 'Polished Maedate', image: 'polishedMaedate', rarity: 'uncommon', frenchName: 'Maedate Lustré' },
            { name: 'Kanal-Anzen Talisman', image: 'kanal-Anzen Talisman', rarity: 'rare', frenchName: 'Talisman Kanal-Anzen' },
            { name: 'Scalped Topknot', image: 'scalpedTopknot', rarity: 'rare', frenchName: 'Chignon Scalpé' },
            { name: 'Shattered Wakizashi', image: 'shatteredWakizashi', rarity: 'rare', frenchName: 'Wakizashi Brisé' },
            { name: 'Wooden Oni Mask', image: 'woodenOniMask', rarity: 'rare', frenchName: 'Masque d\'Oni en Bois' },
            { name: 'Yamaoka Sashimono', image: 'yamaokaSashimono', rarity: 'rare', frenchName: 'Yamaoka Sashimono' },
            { name: 'Akito\'s Crutch', image: 'akitosCrutch', rarity: 'veryrare', frenchName: 'Béquille d\'Akito' },
            { name: 'Lion Fang', image: 'lionFang', rarity: 'veryrare', frenchName: 'Croc de Lion' },
            { name: 'Splintered Hull', image: 'splinteredHull', rarity: 'veryrare', frenchName: 'Coque Éventrée' },
            { name: 'Tear-Soaked Tenugul', image: 'tear-SoakedTenugul', rarity: 'veryrare', frenchName: 'Tenugul Imbibé de Larmes' },
            { name: 'Iridescent Family Crest', image: 'iridescentFamilyCrest', rarity: 'ultra', frenchName: 'Blason de Famille Irisé' },
            { name: 'Renjiro\'s Bloody Glove', image: 'renjirosBloodyGlove', rarity: 'ultra', frenchName: 'Gant Sanglant de Renjiro' }
        ]
    },
    'deathslinger': {
        image: 'theRedeemer',
        addons: [
            { name: 'Modified Ammo Belt', image: 'modifiedAmmoBelt', rarity: 'common', frenchName: 'Ceinture à Munitions Modifiée' },
            { name: 'Rickety Chain', image: 'ricketyChain', rarity: 'common', frenchName: 'Chaîne Fragile' },
            { name: 'Snake Oil', image: 'snakeOil', rarity: 'common', frenchName: 'Poudre de Perlimpinpin' },
            { name: 'Spit Polish Rag', image: 'spitPolishRag', rarity: 'common', frenchName: 'Tissu d\'Astiquage' },
            { name: 'Chewing Tobacco', image: 'chewingTobacco', rarity: 'uncommon', frenchName: 'Tabac à Mâcher' },
            { name: 'Jaw Smasher', image: 'jawSmasher', rarity: 'uncommon', frenchName: 'Casseur de Mâchoire' },
            { name: 'Marshal\'s Badge' , image: 'marshalsBadge', rarity: 'uncommon', frenchName: 'Insigne de Marshal' },
            { name: 'Poison Oak Leaves', image: 'poisonOakLeaves', rarity: 'uncommon', frenchName: 'Feuille de Sumac de l\'Ouest' },
            { name: 'Rusted Spike', image: 'rustedSpikes', rarity: 'uncommon', frenchName: 'Crampon Rouillé' },
            { name: 'Bayshore\'s Gold Tooth', image: 'bayshoresGoldTooth', rarity: 'rare', frenchName: 'Dent en Or de Bayshore' },
            { name: 'Honey Locust Thorn', image: 'honeyLocustThron', rarity: 'rare', frenchName: 'Épines de Févier Épineux' },
            { name: 'Tin Oil Can', image: 'tinOilCan', rarity: 'rare', frenchName: 'Bidon d\'Huile' },
            { name: 'Wanted Poster', image: 'wantedPoster', rarity: 'rare', frenchName: 'Avis de Recherche' },
            { name: 'Warden\'s Keys', image: 'wardensKeys', rarity: 'rare', frenchName: 'Clés du Directeur' },
            { name: 'Barbed Wire', image: 'barbedWire', rarity: 'veryrare', frenchName: 'Fil Barbelé' },
            { name: 'Bayshore\'s Cigar', image: 'bayshoresCigar', rarity: 'veryrare', frenchName: 'Cigare de Bayshore' },
            { name: 'Gold Creek Whiskey', image: 'goldCreekWhiskey', rarity: 'veryrare', frenchName: 'Bourbon Gold Creek' },
            { name: 'Prison Chain', image: 'prisonChain', rarity: 'veryrare', frenchName: 'Chaîne de Prison' },
            { name: 'Hellshire Iron', image: 'hellshireIron', rarity: 'ultra', frenchName: 'Fer de Hellshire' },
            { name: 'Iridescent Coin', image: 'iridescentCoin', rarity: 'ultra', frenchName: 'Pièce Irisée' }
        ]
    },
    'executioner': {
        image: 'ritesOfJudgement',
        addons: [
            { name: 'Black Strap', image: 'blackStrap', rarity: 'common', frenchName: 'Sangle Noire' },
            { name: 'Copper Ring', image: 'copperRing', rarity: 'common', frenchName: 'Anneau de Cuivre' },
            { name: 'Dead Butterfly', image: 'deadButterfly', rarity: 'common', frenchName: 'Papillon Mort' },
            { name: 'Lead Ring', image: 'leadRing', rarity: 'common', frenchName: 'Anneau d\'Étain' },
            { name: 'Cinderella Music Box', image: 'cinderellaMusicBox', rarity: 'uncommon', frenchName: 'Boîte à Musique "Cendrillon"' },
            { name: 'Forgotten Videotape', image: 'forgottenVideotape', rarity: 'uncommon', frenchName: 'Cassette Vidéo Oubliée' },
            { name: 'Leopard-Print Fabric', image: 'leopard-PrintFabric', rarity: 'uncommon', frenchName: 'Tissu à Imprimé Léopard' },
            { name: 'Spearhead', image: 'spearhead', rarity: 'uncommon', frenchName: 'Fer de Lance' },
            { name: 'Wax Doll', image: 'waxDoll', rarity: 'uncommon', frenchName: 'Poupée de Cire' },
            { name: 'Burning Man Painting', image: 'burningManPainting', rarity: 'rare', frenchName: 'Peinture de l\'Homme en Feu' },
            { name: 'Mannequin Foot', image: 'mannequinFoot', rarity: 'rare', frenchName: 'Pied de Mannequin' },
            { name: 'Misty Day, Remains of Judgement', image: 'mistyDayRemainsOfJudgement', rarity: 'rare', frenchName: 'Jour de Brume, Restes du Jugement' },
            { name: 'Tablet of the Oppressor', image: 'tabletOfTheOppressor', rarity: 'rare', frenchName: 'Tablette de l\'Oppresseur' },
            { name: 'Valtiel Sect Photograph', image: 'valtielSectPhotograph', rarity: 'rare', frenchName: 'Photographie de la Secte de Valtiel' },
            { name: 'Crimson Ceremony Book', image: 'crimsonCeremonyBook', rarity: 'veryrare', frenchName: 'Livre "Cérémonie Crimson"' },
            { name: 'Lost Memories Book', image: 'lostMemoriesBook', rarity: 'veryrare', frenchName: 'Livre "Souvenirs Perdus' },
            { name: 'Rust-Coloured Egg', image: 'rust-ColouredEgg', rarity: 'veryrare', frenchName: 'Oeuf Couleur Rouille' },
            { name: 'Scarlet Egg', image: 'scarletEgg', rarity: 'veryrare', frenchName: 'Oeuf Écarlate' },
            { name: 'Iridescent Seal of Metatron', image: 'iridescentSealOfMetatron', rarity: 'ultra', frenchName: 'Sceau de Métatron Irisé' },
            { name: 'Obsidian Goblet', image: 'obsidianGoblet', rarity: 'ultra', frenchName: 'Coupe en Obsidienne' }
        ]
    },
    'blight': {
        image: 'blightedCorruption',
        addons: [
            { name: 'Chipped Monocle', image: 'chippedMonocle', rarity: 'common', frenchName: 'Monocle Ébréché' },
            { name: 'Compound Seven', image: 'compoundSeven', rarity: 'common', frenchName: 'Composé N°7' },
            { name: 'Foxglove', image: 'foxglove', rarity: 'common', frenchName: 'Digitale' },
            { name: 'Placebo Tablet', image: 'placeboTablet', rarity: 'common', frenchName: 'Comprimé Placebo' },
            { name: 'Blighted Rat', image: 'blightedRat', rarity: 'uncommon', frenchName: 'Rat du Fléau' },
            { name: 'Canker Thorn', image: 'cankerThorn', rarity: 'uncommon', frenchName: 'Ronce d\'Ulcère' },
            { name: 'Plague Bile', image: 'plagueBile', rarity: 'uncommon', frenchname: 'Bile de L\'Épidémie' },
            { name: 'Pustula Dust', image: 'pustulaDust', rarity: 'uncommon', frenchName: 'Poussière de Pustulas' },
            { name: 'Shredded Notes', image: 'shreddedNotes', rarity: 'uncommon', frenchName: 'Notes Déchirées' },
            { name: 'Adrenaline Vial', image: 'adrenalineVial', rarity: 'rare', frenchName: 'Tonifiant aux Roses' },
            { name: 'Blighted Crow', image: 'blightedCrow', rarity: 'rare', frenchName: 'Corbeau du Fléau' },
            { name: 'Compound Twenty-One', image: 'compoundTwenty-One', rarity: 'rare', frenchName: 'Composé N°21' },
            { name: 'Rose Tonic', image: 'roseTonic', rarity: 'rare', frenchName: 'Tonifiant aux Roses' },
            { name: 'Umbra Salts', image: 'umbraSalts', rarity: 'rare', frenchName: 'Sels des Ombres' },
            { name: 'Alchemist\'s Ring', image: 'alchemistsRing', rarity: 'veryrare', frenchName: 'Anneau d\'Alchimiste' },
            { name: 'Soul Chemical', image: 'soulChemical', rarity: 'veryrare', frenchName: 'Substance d\'Âme' },
            { name: 'Summoning Stone', image: 'summoningStone', rarity: 'veryrare', frenchName: 'Pierre d\'Invocation' },
            { name: 'Vigo\'s Journal', image: 'vigosJournal', rarity: 'veryrare', frenchName: 'Journal de Vigo' },
            { name: 'Compound Thirty-Three', image: 'compoundThirty-Three', rarity: 'ultra', frenchName: 'Composé N°33' },
            { name: 'Iridescent Blight Tag', image: 'iridescentBlightTag', rarity: 'ultra', frenchName: 'Étiquette Irisée du Fléau' }
        ]
    },
    'twins': {
        image: 'bloodBond',
        addons: [
            { name: 'Cat Figurine', image: 'catFigurine', rarity: 'common', frenchName: 'Figurine de Chat' },
            { name: 'Soured Milk', image: 'souredMilk', rarity: 'common', frenchName: 'Lait Tourné' },
            { name: 'Tiny Fingernail', image: 'tinyFingernail', rarity: 'common', frenchName: 'Petit Ongle' },
            { name: 'Toy Sword', image: 'toySword', rarity: 'common', frenchName: 'Épée de Bois' },
            { name: 'Baby Teeth', image: 'babyTeeth', rarity: 'uncommon', frenchName: 'Dents de Bébé' },
            { name: 'Bloody Black Hood', image: 'bloodyBlackHood', rarity: 'uncommon', frenchName: 'Capuche Noire Sanglante' },
            { name: 'Cat\'s Eye', image: 'catsEye', rarity: 'uncommon', frenchName: 'Oeil de Chat' },
            { name: 'Ceremonial Candelabrum', image: 'ceremonialCandel', rarity: 'uncommon', frenchName: 'Candélabre Cérémoniel' },
            { name: 'Madeleine\'s Glove', image: 'madeleinesGlove', rarity: 'uncommon', frenchName: 'Gant de Madeleine' },
            { name: 'Madeleine\'s Scarf', image: 'madeleinesScarf', rarity: 'rare', frenchName: 'Écharpe de Madeleine' },
            { name: 'Rusted Needle', image: 'rustedNeedle', rarity: 'rare', frenchName: 'Aiguille Rouillée' },
            { name: 'Sewer Sludge', image: 'sewerSludge', rarity: 'rare', frenchName: 'Vase des Égouts' },
            { name: 'Stale Biscuit', image: 'staleBiscuit', rarity: 'rare', frenchName: 'Biscuit Rassis' },
            { name: 'Weighty Rattle', image: 'weightyRattle', rarity: 'rare', frenchName: 'Hochet Lourd' },
            { name: 'Drop of Perfume', image: 'dropOfPerfume', rarity: 'veryrare', frenchName: 'Goutte de Parfum' },
            { name: 'Forest Stew', image: 'forestStew', rarity: 'veryrare', frenchName: 'Potage des Bois' },
            { name: 'Spinning Top', image: 'spinningTop', rarity: 'veryrare', frenchName: 'Toupie' },
            { name: 'Victor\'s Soldier', image: 'victorsSoldier', rarity: 'veryrare', frenchName: 'Petit Soldat de Victor' },
            { name: 'Iridescent Pendant', image: 'iridescentPendant', rarity: 'ultra', frenchName: 'Pendentif Irisé' },
            { name: 'SilencingCloth', image: 'silencingCloth', rarity: 'ultra', frenchName: 'Bâillon' }
        ]
    },
    'trickster': {
        image: 'showstopper',
        addons: [
            { name: 'Inferno Wires', image: 'infernoWires', rarity: 'common', frenchName: 'Câbles Infernaux' },
            { name: 'Killing Part Chords', image: 'killingPartChords', rarity: 'common', frenchName: 'Accords de Partition Mortels' },
            { name: 'Memento Blades', image: 'mementoBlades', rarity: 'common', frenchName: 'Lames Souvenirs' },
            { name: 'Trick Pouch', image: 'trickPouch', rarity: 'common', frenchName: 'Sac à Malice' },
            { name: 'Caged Heart Shoes', image: 'cagedHeartShoes', rarity: 'uncommon', frenchName: 'Chaussures One Caged Heart' },
            { name: 'Ji-Woon\'s Autograph', image: 'ji-WoonsAutograph', rarity: 'uncommon', frenchName: 'Autographe de Ji-Woon' },
            { name: 'Lucky Blade', image: 'luckyBlade', rarity: 'uncommon', frenchName: 'Lame Porte-Bonheur' },
            { name: 'OnTarget Single', image: 'onTargetSingle', rarity: 'uncommon', frenchName: 'Lancer Précis' },
            { name: 'Tequila Moonrock', image: 'tequilaMoonrock', rarity: 'uncommon', frenchName: 'Tequila Sélénite' },
            { name: 'Bloody Boa', image: 'bloodyBoa', rarity: 'rare', frenchName: 'Boa Sanglant' },
            { name: 'Fizz-Spin Soda', image: 'fizz-SpinSoda', rarity: 'rare', frenchName: 'Soda Fizz-Spin' },
            { name: 'Melodious Murder', image: 'melodiousMurder', rarity: 'rare', frenchName: 'Meurtre Mélodieux' },
            { name: 'Ripper Brace', image: 'ripperBrace', rarity: 'rare', frenchName: 'Protège-Poignet de Ripper' },
            { name: 'Waiting For You Watch', image: 'waitingForYouWatch', rarity: 'rare', frenchName: 'Montre Waiting For You' },
            { name: 'Cut Thru U Single', image: 'cutThruUSingle', rarity: 'veryrare', frenchName: 'Single Cut Thru U' },
            { name: 'Diamond Cufflinks', image: 'diamondCufflinks', rarity: 'veryrare', frenchName: 'Boutons de Manchette en Diamant' },
            { name: 'Edge of Revival Album', image: 'edgeOfRevivalAlbum', rarity: 'veryrare', frenchName: 'Album Edge of Revival' },
            { name: 'Trick Blades', image: 'trickBlades', rarity: 'veryrare', frenchName: 'Lames Truquées' },
            { name: 'Death Troes Compilation', image: 'deathTroesCompilation', rarity: 'ultra', frenchName: 'Compilation d\'Agonies Mortelles' },
            { name: 'Iridescent Photocard', image: 'iridescentPhotocard', rarity: 'ultra', frenchName: 'Photo Irisée' }
        ]
    },
    'nemesis': {
        image: 't-Virus',
        addons: [
            { name: 'Brian\'s Intestine', image: 'briansIntestine', rarity: 'common', frenchName: 'Intestin de Brian' },
            { name: 'Damaged Syringe', image: 'damagedSyringe', rarity: 'common', frenchName: 'Seringue Abîmée' },
            { name: 'S.T.A.R.S. Field Combat Manual', image: 'starsFieldCombatManual', rarity: 'common', frenchName: 'Manuel de Combat du S.T.A.R.S.' },
            { name: 'Visitor Wristband', image: 'visitorWristband', rarity: 'common', frenchName: 'Bracelet de Visiteur' },
            { name: 'Admin Wristband', image: 'adminWristband', rarity: 'uncommon', frenchName: 'Bracelet d\'Administrateur' },
            { name: 'Adrenaline Injector', image: 'adrenalineInjector', rarity: 'uncommon', frenchName: 'Injecteur d\'Adrénaline' },
            { name: 'Marvin\'s Blood', image: 'marvinsBlood', rarity: 'uncommon', frenchName: 'Sang de Marvin' },
            { name: 'Mikhail\'s Eye', image: 'mikhailsEye', rarity: 'uncommon', frenchName: 'Oeil de Mikhail' },
            { name: 'Zombie Heart', image: 'zombieHeart', rarity: 'uncommon', frenchName: 'Coeur de Zombie' },
            { name: 'Licker Tongue', image: 'lickerTongue', rarity: 'rare', frenchName: 'Langue de Licker' },
            { name: 'Plant 43 Vines', image: 'plant43Vines', rarity: 'rare', frenchName: 'Lianes de Plante 43' },
            { name: 'Serotonin Injector', image: 'serotoninInjector', rarity: 'rare', frenchName: 'Injecteur de Sérotonine' },
            { name: 'T-Virus Sample', image: 't-VirusSample', rarity: 'rare', frenchName: 'Échantillon du Virus T' },
            { name: 'Tyrant Gore', image: 'tyrantGore', rarity: 'rare', frenchName: 'Carnage de Tyrant' },
            { name: 'Broken Recovery Coin', image: 'brokenRecoveryCoin', rarity: 'veryrare', frenchName: 'Pièce de Récupération Brisée' },
            { name: 'Depleted Ink Ribbon', image: 'depletedInkRibbon', rarity: 'veryrare', frenchName: 'Ruban d\'Encre Vide' },
            { name: 'Jill\'s Sandwich', image: 'jillsSandwich', rarity: 'veryrare', frenchName: 'Sandwich de Jill' },
            { name: 'Ne-a Parasite', image: 'ne-aParasite', rarity: 'veryrare', frenchName: 'Parasite Ne-a' },
            { name: 'Iridescent Umbrella Badge', image: 'iridescentUmbrellaBadge', rarity: 'ultra', frenchName: 'Insigne Irisé d\'Umbrella' },
            { name: 'Shattered S.T.A.R.S. Badge', image: 'shatteredSTARSBadge', rarity: 'ultra', frenchName: 'Insigne Brisé du S.T.A.R.S.' }
        ]
    },
    'cenobite': {
        image: 'summonsOfPain',
        addons: [
            { name: 'Bent Nail', image: 'bentNail', rarity: 'common', frenchName: 'Clou Tordu' },
            { name: 'Burning Candle', image: 'burningCandle', rarity: 'common', frenchName: 'Bougie Incandescente' },
            { name: 'Leather Strip', image: 'leatherStrip', rarity: 'common', frenchName: 'Bandes en Cuir' },
            { name: 'Lively Crickets', image: 'livelyCrickets', rarity: 'common', frenchName: 'Grillons Vivants' },
            { name: 'Flickering Television', image: 'flickeringTelevision', rarity: 'uncommon', frenchName: 'Télévision Clignotante' },
            { name: 'Liquified Gore', image: 'liquifiedGore', rarity: 'uncommon', frenchName: 'Tripes Liquéfiées' },
            { name: 'Skewered Rat', image: 'skeweredRat', rarity: 'uncommon', frenchName: 'Brochette de Rat' },
            { name: 'Spoiled Meal', image: 'spoiledMeal', rarity: 'uncommon', frenchName: 'Viande Gâtée' },
            { name: 'Wriggling Maggots', image: 'wrigglingMaggots', rarity: 'uncommon', frenchName: 'Vers Agités' },
            { name: 'Frank\'s Heart', image: 'franksHeart', rarity: 'rare', frenchName: 'Coeur de Frank' },
            { name: 'Larry\'s Blood', image: 'larrysBlood', rarity: 'rare', frenchname: 'Sang de Larry' },
            { name: 'Larry\'s Remains', image: 'larrysRemains', rarity: 'rare', frenchName: 'Restes de Larry' },
            { name: 'Slice of Frank', image: 'sliceOfFrank', rarity: 'rare', frenchName: 'Tranche de Frank' },
            { name: 'Torture Pillar', image: 'torturePillar', rarity: 'rare', frenchName: 'Piller de Torture' },
            { name: 'Chatterer\'s Tooth', image: 'chatterersTooth', rarity: 'veryrare', frenchName: 'Dent du Bavard' },
            { name: 'Greasy Black Lens', image: 'greasyBlackLens', rarity: 'veryrare', frenchName: 'Verre Noire Couvert de Graisse' },
            { name: 'Impaling Wire', image: 'impalingWire', rarity: 'veryrare', frenchName: 'Câble à Empaler' },
            { name: 'Original Pain', image: 'originalPain', rarity: 'veryrare', frenchName: 'Douleur Originale' },
            { name: 'Engineer\'s Fang', image: 'engineersFang', rarity: 'ultra', frenchName: 'Croc d\'Ingénieur' },
            { name: 'Iridescent Lament Configuration', image: 'iridescentLamentConfiguration', rarity: 'ultra', frenchName: 'Configuration des Lamentations Irisée' }
        ]
    },
    'artist': {
        image: 'birdsOfTorment',
        addons: [
            { name: 'Choclo Corn', image: 'chocloCorn', rarity: 'common', frenchName: 'Maïs Choclo' },
            { name: 'Oil Paints', image: 'oilPaints', rarity: 'common', frenchName: 'Peintures à l\'Huile' },
            { name: 'Thick Tar', image: 'thickTar', rarity: 'common', frenchName: 'Goudron Épais' },
            { name: 'Vibrant Obituary', image: 'vibrantObituary', rarity: 'common', frenchName: 'Vibrant Avis de Décès' },
            { name: 'Automatic Drawing', image: 'automaticDrawing', rarity: 'uncommon', frenchName: 'Dessin Automatique' },
            { name: 'Festering Carrion', image: 'festeringCarrion', rarity: 'uncommon', frenchName: 'Charogne Pourrissante' },
            { name: 'Still Life Crow', image: 'stillLifeCrow', rarity: 'uncommon', frenchName: 'Corbeau de Nature Morte' },
            { name: 'Untitled Agony', image: 'untitledAgony', rarity: 'uncommon', frenchName: 'Agonie Sans Titre' },
            { name: 'Velvet Fabric', image: 'velvetFabric', rarity: 'uncommon', frenchName: 'Tissu en Velours' },
            { name: 'Charcoal Stick', image: 'charcoalStick', rarity: 'rare', frenchName: 'Bout de Charbon' },
            { name: 'Darkest Ink', image: 'darkestInk', rarity: 'rare', frenchName: 'Encre Ténébreuse' },
            { name: 'O Grief, O Lover', image: 'oGriefOLover', rarity: 'rare', frenchName: 'Ô Chagrin d\'Amour' },
            { name: 'Silver Bell', image: 'silverBell', rarity: 'rare', frenchName: 'Clochette d\'Argent' },
            { name: 'Thorny Nest', image: 'thornyNest', rarity:' rare', frenchName: 'Nid Épineux' },
            { name: 'Ink Egg', image: 'inkEgg', rarity: 'veryrare', frenchName: 'Oeuf d\'Encre' },
            { name: 'Matias\' Baby Shoes', image: 'matiasBabyShoes', rarity: 'veryrare', frenchName: 'Chaussures de Bébé de Matias' },
            { name: 'Severed Hands', image: 'severedHands', rarity: 'veryrare', frenchName: 'Mains Tranchées' },
            { name: 'Severed Tongue', image: 'severedTongue', rarity: 'veryrare', frenchName: 'Langue Tranchée' },
            { name: 'Garden of Rot', image: 'gardenOfRot', rarity: 'ultra', frenchName: 'Jardin de Pourriture' },
            { name: 'Iridescent Feather', image: 'iridescentFeather', rarity: 'ultra', frenchName: 'Plume Irisé' }
        ]
    },
    'onryo': {
        image: 'delugeOfFear',
        addons: [
            { name: 'Cabin Sign', image: 'cabinSign', rarity: 'common', frenchName: 'Panneau du Chalet' },
            { name: 'Mother\'s Mirror', image: 'mothersMirror', rarity: 'common', frenchName: 'Miroir de la Mère' },
            { name: 'Old Newspaper', image: 'oldNewspaper', rarity: 'common', frenchName: 'Vieux Journal' },
            { name: 'Videotape Copy', image: 'videotapeCopy', rarity: 'common', frenchName: 'Copie de Cassette Vidéo' },
            { name: 'Clump of Hair', image: 'clumpOfHair', rarity: 'uncommon', frenchName: 'Poignée de Cheveux' },
            { name: 'Reiko\'s Watch', image: 'reikosWatch', rarity: 'uncommon', frenchName: 'Montre de Reiko' },
            { name: 'Sea-Soaked Cloth', image: 'sea-SoakedCloth', rarity: 'uncommon', frenchName: 'Vêtement Trempé d\'Eau de Mer' },
            { name: 'Well Stone', image: 'wellStone', rarity: 'uncommon', frenchName: 'Puits en Pierre' },
            { name: 'Yoichi\'s Fishing Net', image: 'yoichisFishingNet', rarity: 'uncommon', frenchName: 'Filet de Pêche de Yoichi' },
            { name: 'Bloody Fingernails', image: 'bloodyFingernails', rarity: 'rare', frenchName: 'Ongles Sanglants' },
            { name: 'Mother\'s Comb', image: 'mothersComb', rarity: 'rare', frenchName: 'Peigne de la Mère' },
            { name: 'Rickety Pinwheel', image: 'ricketyPinwheel', rarity: 'rare', frenchName: 'Moulin à Vent Bancal' },
            { name: 'Ring Drawing', image: 'ringDrawing', rarity: 'rare', frenchName: 'Dessin d\'un Cercle' },
            { name: 'Well Water', image: 'wellWater', rarity: 'rare', frenchName: 'Eau de Puits' },
            { name: 'Distorted Photo', image: 'distortedPhoto', rarity: 'veryrare', frenchName: 'Photo Déformée' },
            { name: 'Tape Editing Deck', image: 'tapeEditingDeck', rarity: 'veryrare', frenchName: 'Pupitre de Montage de Cassette' },
            { name: 'Telephone', image: 'telephone', rarity: 'veryrare', frenchName: 'Téléphone' },
            { name: 'VCR', image: 'vcr', rarity: 'veryrare', frenchName: 'Magnétoscope' },
            { name: 'Iridescent Videotape', image: 'iridescentVideotape', rarity: 'ultra', frenchName: 'Cassette Vidéo Irisée' },
            { name: 'Remote Control', image: 'remoteControl', rarity: 'ultra', frenchName: 'Télécommande' }
        ]
    },
    'dredge': {
        image: 'reignOfDarkness',
        addons: [
            { name: 'Caffeine Tablets', image: 'caffeineTablets', rarity: 'common', frenchName: 'Comprimés de Caféine' },
            { name: 'Follower\'s Cowl', image: 'followersCowl', rarity: 'common', frenchName: 'Capuche de Fidèle' },
            { name: 'Mortar and Pestle', image: 'mortarAndPestle', rarity: 'common', frenchName: 'Pilon et Mortier' },
            { name: 'Wooden Plank', image: 'woodenPlank', rarity: 'common', frenchName: 'Planche en Bois' },
            { name: 'Air Freshener', image: 'airFreshener', rarity: 'uncommon', frenchName: 'Désodorisant' },
            { name: 'Burnt Letters', image: 'burntLetters', rarity: 'uncommon', frenchName: 'Lettres Brûlées' },
            { name: 'Fallen Shingle', image: 'fallenShingle', rarity: 'uncommon', frenchName: 'Bardeau Tombé' },
            { name: 'Haddie\'s Calendar', image: 'haddiesCalendar', rarity: 'uncommon', frenchName: 'Calendrier de Haddie' },
            { name: 'Malthinker\'s Skull', image: 'malthinkersSkull', rarity: 'uncommon', frenchName: 'Crâne de Malpenseur' },
            { name: 'Broken Doll', image: 'brokenDoll', rarity: 'rare', frenchName: 'Poupée Brisée' },
            { name: 'Destroyed Pillow', image: 'destroyedPillow', rarity: 'rare', frenchName: 'Oreiller Détruit' },
            { name: 'Ottomarian Writing', image: 'ottomarianWriting', rarity: 'rare', frenchName: 'Écrits d\'Ottomarien' },
            { name: 'War Helmet', image: 'warHelmet', rarity: 'rare', frenchName: 'Casque de Guerre' },
            { name: 'Worry Stone', image: 'worryStone', rarity: 'rare', frenchName: 'Pierre de Soucis' },
            { name: 'Boat Key', image: 'boatKey', rarity: 'veryrare', frenchName: 'Clé de Bateau' },
            { name: 'Field Recorder', image: 'fieldRecorder', rarity: 'veryrare', frenchName: 'Enregistreur de Terrain' },
            { name: 'Lavalier Microphone', image: 'lavalierMicrophone', rarity: 'veryrare', frenchName: 'Micro-Cravate' },
            { name: 'Tilling Blade', image: 'tillingBlade', rarity: 'veryrare', frenchName: 'Lame de Labourage' },
            { name: 'Iridescent Wooden Plank', image: 'iridescentWoodenPlank', rarity: 'ultra', frenchName: 'Planche en Bois Iridescente' },
            { name: 'Sacrificial Knife', image: 'sacrificialKnife', rarity: 'ultra', frenchName: 'Couteau Sacrificiel' }
        ]
    },
    'mastermind': {
        image: 'virulentBond',
        addons: [
            { name: 'Jewel Beetle', image: 'jewelBeetle', rarity: 'common', frenchName: 'Scarabée Précieux' },
            { name: 'R.P.D. Shoulder Walkie', image: 'rpdShoulderWalkie', rarity: 'common', frenchName: 'Talkie d\'Épaule du R.P.D.' },
            { name: 'Unicorn Medallion', image: 'unicornMedallion', rarity: 'common', frenchName: 'Médaillon Licorne' },
            { name: 'Uroboros Tendril', image: 'uroborosTendril', rarity: 'common', frenchName: 'Vrille d\'Uroboros' },
            { name: 'Bullhorn', image: 'bullhorn', rarity: 'uncommon', frenchName: 'Porte-Voix' },
            { name: 'Chalice (Gold)', image: 'chaliceGold', rarity: 'uncommon', frenchName: 'Calice (Or)' },
            { name: 'Leather Gloves', image: 'leatherGloves', rarity: 'uncommon', frenchName: 'Gants en Cuir' },
            { name: 'Lion Medallion', image: 'lionMedallion', rarity: 'uncommon', frenchName: 'Médaillon Lion' },
            { name: 'Loose Crank', image: 'looseCrank', rarity: 'uncommon', frenchName: 'Manivelle Lâche' },
            { name: 'Egg (Gold)', image: 'eggGold', rarity: 'rare', frenchName: 'Oeuf (Doré)' },
            { name: 'Maiden Medallion', image: 'maidenMedallion', rarity: 'rare', frenchName: 'Médaillon Jeune Fille' },
            { name: 'Portable Safe', image: 'portableSafe', rarity: 'rare', frenchName: 'Coffre Portatif' },
            { name: 'Red Herb', image: 'redHerb', rarity: 'rare', frenchName: 'Plante Rouge' },
            { name: 'Video Conference Device', image: 'videoConferenceDevice', rarity: 'rare', frenchName: 'Appareil de Vidéo Conférence' },
            { name: 'Dark Sunglasses', image: 'darkSunglasses', rarity: 'veryrare', frenchName: 'Lunettes de Soleil Sombres' },
            { name: 'Green Herb', image: 'greenHerb', rarity: 'veryrare', frenchName: 'Plante Verte' },
            { name: 'Helicopter Stick', image: 'helicopterStick', rarity: 'veryrare', frenchName: 'Manche d\'Hélicoptère' },
            { name: 'Uroboros Virus', image: 'uroborosVirus', rarity: 'veryrare', frenchName: 'Virus Uroboros' },
            { name: 'Iridescent Uroboros Vial', image: 'iridescentUroborosVial', rarity: 'ultra', frenchName: 'Éprouvette d\'Uroboros Irisée' },
            { name: 'Lab Photo', image: 'labPhoto', rarity: 'ultra', frenchName: 'Photo de Labo' }
        ]
    },
    'knight': {
        image: 'guardiaCompagnia',
        addons: [
            { name: 'Gritty Lump', image: 'grittyLump', rarity: 'common', frenchName: 'Miche Grumeleuse' }
            { name: 'Map of the Realm', image: 'mapOfTheRealm', rarity: 'common', frenchName: 'Carte du Royaume' },
            { name: 'Pillaged Mead', image: 'pillagedMead', rarity: 'common', frenchName: 'Hydromel Pillé' },
            { name: 'Tattered Tabard', image: 'tatteredTabard', rarity: 'common', frenchName: 'Tabard en Lambeaux' },
            { name: 'Battle Axe Head', image: 'battleAxeHead', rarity: 'uncommon', frenchName: 'Fer de Hache de Guerre' },
            { name: 'Call to Arms', image: 'callToArms', rarity: 'uncommon', frenchName: 'Appel aux Armes' },
            { name: 'Cold Steel Manacles', image: 'coldSteelManacles', rarity: 'uncommon', frenchName: 'Menottes en Acier Froid' },
            { name: 'Dried Horsemeat', image: 'driedHorsemeat', rarity: 'uncommon', frenchName: 'Viande de Cheval Séchée' },
            { name: 'Treated Blade', image: 'treatedBlade', rarity: 'uncommon', frenchName: 'Lame Traitée' },
            { name: 'Broken Hilt', image: 'brokenHilt', rarity: 'rare', frenchName: 'Poignée Brisée' },
            { name: 'Chain Mail Fragment', image: 'chainMailFragment', rarity: 'rare', frenchName: 'Fragment de Cotte de Mailles' },
            { name: 'Grim Iron Mask', image: 'grimIronMask', rarity: 'rare', frenchName: 'Masque de Fer Sinistre' },
            { name: 'Ironworker\'s Tongs', image: 'ironworkersTongs', rarity: 'rare', frenchName: 'Pinces de Ferronnier' },
            { name: 'Town Watch\'s Torch', image: 'townWatchsTorch', rarity: 'rare', frenchName: 'Torche du Guet de la Ville' },
            { name: 'Blacksmith\'s Hammer', image: 'blacksmithsHammer', rarity: 'veryrare', frenchName: 'Marteau de Forgeron' },
            { name: 'Flint and Steel', image: 'flintAndSteel', rarity: 'veryrare', frenchName: 'Silex et Acier' },
            { name: 'Healing Poultice', image: 'healingPoultice', rarity: 'veryrare', frenchName: 'Cataplasme Curatif' },
            { name: 'Lightweight Greaves', image: 'lightweightGreaves', rarity: 'veryrare', frenchName: 'Grèves Légères' },
            { name: 'Iridescent Company Banner', image: 'iridescentCompanyBanner', rarity: 'ultra', frenchName: 'Bannière de Compagnie Irisée' },
            { name: 'Knight\'s Contract', image: 'knightsContract', rarity: 'ultra', frenchName: 'Contrat du Chevalier' }
        ]
    },
    'skullmerchant': {
        image: 'eyesInTheSky',
        addons: [
            { name: 'Adi Valente Issue 1', image: 'adiValenteIssue1', rarity: 'common', frenchName: 'Adi Valente N° 1' },
            { name: 'High-Current Upgrade', image: 'high-CurrentUpgrade', rarity: 'common', frenchName: 'Haute Amélioration de Courant' },
            { name: 'High-Power Floodlight', image: 'high-PowerFloodlight', rarity: 'common', frenchName: 'Projecteur Surpuissant' },
            { name: 'Ultrasonic Speaker', image: 'ultrasonicSpeaker', rarity: 'common', frenchName: 'Haut-Parleur Ultrasonique' },
            { name: 'Adaptive Lighting', image: 'adaptiveLighting', rarity: 'uncommon', frenchName: 'Éclairage Adaptatif' },
            { name: 'Low-Power Mode', image: 'low-PowerMode', rarity: 'uncommon', frenchName: 'Mode Basse Consommation' },
            { name: 'Shotgun Speakers', image: 'shotgunSpeakers', rarity: 'uncommon', frenchName: 'Haut-Parleurs Directionnels' },
            { name: 'Stereo Remote Mic', image: 'stereoRemoteMic', rarity: 'uncommon', frenchName: 'Micro à Distance Stéréo' },
            { name: 'Supercharge', image: 'supercharge', rarity: 'uncommon', frenchName: 'Supercharge' },
            { name: 'Brown Noise Generator', image: 'brownNoiseGenerator', rarity: 'rare', frenchName: 'Générateur de Bruit Brun' },
            { name: 'Infrared Upgrade', image: 'infraredUpgrade', rarity: 'rare', frenchName: 'Amélioration Infrarouge' },
            { name: 'Loose Screw', image: 'looseScrew', rarity: 'rare', frenchName: 'Vis Lâche' },
            { name: 'Powdered Glass', image: 'powderedGlass', rarity: 'rare', frenchName: 'Poudre de Verre' },
            { name: 'Vital Targeting Processor', image: 'vitalTargetingProcessor', rarity: 'rare', frenchName: 'Processeur de Ciblage Vital' },
            { name: 'Advanced Movement Prediction', image: 'advancedMovementPrediction', rarity: 'veryrare', frenchName: 'Prédiction de Déplacement Avancé' },
            { name: 'Geographical Readout', image: 'geographicalReadout', rarity: 'veryrare', frenchName: 'Relevé Géographique' },
            { name: 'Prototype Rotor', image: 'prototypeRotor', rarity: 'veryrare', frenchName: 'Rotor de Prototype' },
            { name: 'Randomised Strobes', image: 'randomisedStrobes', rarity: 'veryrare', frenchName: 'Lumières Stoboscopiques Aléatoires' },
            { name: 'Expired Batteries', image: 'expiredBatteries', rarity: 'ultra', frenchName: 'Piles Périmées' },
            { name: 'Iridescent Unpublished Manuscript', image: 'iridescentUnpublishedManuscript', rarity: 'ultra', frenchName: 'Manuscrit Non Publié Irisé' }
        ]
    },
    'singularity': {
        image: 'quantumInstantiation',
        addons: [
            { name: 'Broken Security Key', image: 'brokenSecurityKey', rarity: 'common', frenchName: 'Clé de Sécurité Cassée' },
            { name: 'Heavy Water', image: 'heavyWater', rarity: 'common', frenchName: 'Eau Lourde' },
            { name: 'Kid\'s Ball Glove', image: 'kidsBallGlove', rarity: 'common', frenchName: 'Gant de Baseball d\'Enfant' },
            { name: 'Nutritional Slurry', image: 'nutritionalSlurry', rarity: 'common', frenchName: 'Bouillie Nutritive' },
            { name: 'Android Arm', image: 'androidArm', rarity: 'uncommon', frenchName: 'Bras d\'Androïde' },
            { name: 'Cremated Remains', image: 'crematedRemains', rarity: 'uncommon', frenchName: 'Restes Incinérés' },
            { name: 'Cryo Gel', image: 'cryoGel', rarity: 'uncommon', frenchName: 'Gel Cryogénique' },
            { name: 'Diagnostic Tool (Repair)', image: 'diagnosticToolRepair', rarity: 'uncommon', frenchName: 'Outil de Diagnostique (Réparation)' },
            { name: 'Ultrasonic Sensor', image: 'ultrasonicSensor', rarity: 'uncommon', frenchName: 'Détecteur Ultrasonique' },
            { name: 'Hologram Generator', image: 'hologramGenerator', rarity: 'rare', frenchName: 'Générateur d\'Hologrammes' },
            { name: 'Hyperawareness Spray', image: 'hyperawarenessSpray', rarity: 'rare', frenchName: 'Aérosol d\'Hypervigilance' },
            { name: 'Live Wires', image: 'liveWires', rarity: 'rare', frenchName: 'Fils Sous Tension' },
            { name: 'Nanomachine Gel', image: 'nanomachineGel', rarity: 'rare', frenchName: 'Gel de Nanomachines' },
            { name: 'Spent Oxygen Tank', image: 'spentOxygenTank', rarity: 'rare', frenchName: 'Bonbonne d\'Oxygène Vide' },
            { name: 'Crew Manifest', image: 'crewManifest', rarity: 'veryrare', frenchName: 'Manifeste de l\'Équipage' },
            { name: 'Diagnostic Tool (Construction)', image: 'diagnosticToolConstruction', rarity: 'veryrare', frenchName: 'Outil de Diagnostique (Construction)' },
            { name: 'Foreign Plant Fibres', image: 'foreignPlantFibres', rarity: 'veryrare', frenchName: 'Fibres de Plante Étrangère' },
            { name: 'Soma Family Photo', image: 'somaFamilyPhoto', rarity: 'veryrare', frenchName: 'Photo de la Famille Soma' },
            { name: 'Denied Requisition Form', image: 'deniedRequisitionForm', rarity: 'ultra', frenchName: 'Formulaire de Réquisition Refusée' },
            { name: 'Iridescent Crystal Shard', image: 'iridescentCrystalShard', rarity: 'ultra', frenchName: 'Éclat de Cristal Irisé' }
        ]
    },
    'xenomorph': {
        image: 'hiddenPursuit',
        addons: [
            { name: 'Cereal Rations', image: 'cerealRations', rarity: 'common', frenchName: 'Rations de Céréales' },
            { name: 'Drinking Bird', image: 'drinkingBird', rarity: 'common', frenchName: 'Buveur' },
            { name: 'Ovomorph', image: 'ovomorph', rarity: 'common', frenchName: 'Ovomorphe' },
            { name: 'Ripley\'s Watch', image: 'ripleysWatch', rarity: 'common', frenchName: 'Montre de Ripley' },
            { name: 'Ash\'s Innards', image: 'ashsInnards', rarity: 'uncommon', frenchName: 'Entrailles de Ash' },
            { name: 'Brett\'s Cap', image: 'brettsCap', rarity: 'uncommon', frenchName: 'Casquette de Brett' },
            { name: 'Crew Headset', image: 'crewHeadset', rarity: 'uncommon', frenchName: 'Casque Audio d\'Équipage' },
            { name: 'Lambert\'s Star Map', image: 'lambertsStarMap', rarity: 'uncommon', frenchName: 'Carte Stellaire de Lambert' },
            { name: 'Light Wand', image: 'lightWand', rarity: 'uncommon', frenchName: 'Bâton de Lumière' },
            { name: 'Emergency Helmet', image: 'emergencyHelmet', rarity: 'rare', frenchName: 'Casque d\'Urgence' },
            { name: 'Kane\'s Helmet', image: 'kanesHelmet', rarity: 'rare', frenchName: 'Casque de Kane' },
            { name: 'Moulted Skin', image: 'moultedSkin', rarity: 'rare', frenchName: 'Peau en Fusion' },
            { name: 'Multipurpose Hatchet', image: 'multipurposeHatchet', rarity: 'rare', frenchName: 'Hachette Polyvalente' },
            { name: 'Parker\'s Headband', image: 'parkersHeadband', rarity: 'rare', frenchName: 'Bandeau de Parker' },
            { name: 'Cat Carrier', image: 'catCarrier', rarity: 'veryrare', frenchName: 'Caisse de Transport du Chat' },
            { name: 'Harpoon Gun', image: 'harpoonGun', rarity: 'veryrare', frenchName: 'Lance-Grappin' },
            { name: 'Self-Destruct Bolt', image: 'self-DestructBolt', rarity: 'veryrare', frenchName: 'Boulon d\'Autodestruction' },
            { name: 'Semiotic Keyboard', image: 'semioticKeyboard', rarity: 'veryrare', frenchName: 'Clavier Sémiotique' },
            { name: 'Acidic Blood', image: 'acidicBlood', rarity: 'ultra', frenchName: 'Sang Acide' },
            { name: 'Improvised Cattle Prod', image: 'improvisedCattleProd', rarity: 'ultra', frenchName: 'Aiguillon Amélioré' }
        ]
    },
    'goodguy': {
        image: 'playtimesOver',
        addons: [
            { name: 'Doll Eyes', image: 'dollEyes', rarity: 'common', frenchName: 'Yeux de Poupée' },
            { name: 'Good Guy Box', image: 'goodGuyBox', rarity: 'common', frenchName: 'Boîte de Brave Gars' },
            { name: 'Strobing Light', image: 'strobingLight', rarity: 'common', frenchName: 'Lumière Stroboscopique' },
            { name: 'Tiny Scalpel', image: 'tinyScalpel', rarity: 'common', frenchName: 'Scalpel Minuscule' },
            { name: 'Automatic Screwdriver', image: 'automaticScrewdriver', rarity: 'uncommon', frenchName: 'Tournevis Automatique' },
            { name: 'Electric Carving Knife', image: 'electricCarvingKnife', rarity: 'uncommon', frenchName: 'Couteau à Découper Électrique' },
            { name: 'Hair Spray & Candle', image: 'hairSpray&Candle', rarity: 'uncommon', frenchName: 'Laque pour Cheveux et Bougie' },
            { name: 'Jump Rope', image: 'jumpRope', rarity: 'uncommon', frenchName: 'Corde à Sauter' },
            { name: 'Power Drill', image: 'powerDrill', rarity: 'uncommon', frenchName: 'Perceuse' },
            { name: 'Portable TV', image: 'portableTV', rarity: 'rare', frenchName: 'Télé Portable' },
            { name: 'Rat Poison', image: 'ratPoison', rarity: 'rare', frenchName: 'Mort-aux-Rats' },
            { name: 'Running Shoes', image: 'runningShoes', rarity: 'rare', frenchName: 'Chaussures de Course' },
            { name: 'Silk Pillow', image: 'silkPillow', rarity: 'rare', frenchName: 'Oreiller en Soie' },
            { name: 'Yardstick', image: 'yardstick', rarity: 'rare', frenchName: 'Règle en Bois' },
            { name: 'Mirror Shards', image: 'mirrorShards', rarity: 'veryrare', frenchName: 'Éclats de Miroir' },
            { name: 'Pile of Nails', image: 'pileOfNails', rarity: 'veryrare', frenchName: 'Tas de Clous' },
            { name: 'Plastic Bag', image: 'plasticBag', rarity: 'veryrare', frenchName: 'Sac en Plastique' },
            { name: 'Straight Razor', image: 'straightRazor', rarity: 'veryrare', frenchName: 'Rasoir Droit' },
            { name: 'Hard Hat', image: 'hardHat', rarity: 'ultra', frenchName: 'Casque de Sécurité' },
            { name: 'Iridescent Amulet', image: 'iridescentAmulet', rarity: 'ultra', frenchName: 'Amulette Irisée' }
        ]
    },
    'unknown': {
        image: 'uvx',
        addons: [
            { name: 'Blurry Photo', image: 'blurryPhoto', rarity: 'common', frenchName: 'Photo Floue' },
            { name: 'Punctured Eyeball', image: 'puncturedEyeball', rarity: 'common', frenchName: 'Globe Oculaire Percé' },
            { name: 'Rabbit\'s Foot', image: 'rabbitsFoot', rarity: 'common', frenchName: 'Patte de Lapin' },
            { name: 'Sketch Attempt', image: 'sketchAttempt', rarity: 'common', frenchName: 'Tentative d\'Esquisse' },
            { name: 'Device of Undisclosed Origin', image: 'deviceOfUndisclosedOrigin', rarity: 'uncommon', frenchName: 'Dispositif d\'Origine Inconnue' },
            { name: 'Last Known Recording', image: 'lastKnownRecording', rarity: 'uncommon', frenchName: 'Dernier Enregistrement Connu' },
            { name: 'Notebook of Theories', image: 'notebookOfTheories', rarity: 'uncommon', frenchName: 'Carnet de Théories' },
            { name: 'Slashed Backpack', image: 'slashedBackpack', rarity: 'uncommon', frenchName: 'Sac à Dos Lacéré' },
            { name: 'Victim\'s Map', image: 'victimsMap', rarity: 'uncommon', frenchName: 'Carte de la Victime' },
            { name: 'B-Movie Poster', image: 'b-MoviePoster', rarity: 'rare', frenchName: 'Poster de Film de Série B' },
            { name: 'Footprint Cast', image: 'footprintCast', rarity: 'rare', frenchName: 'Moulage d\'Empreinte de Pas' },
            { name: 'Front-Page Article', image: 'front-PageArticle', rarity: 'rare', frenchName: 'Article de Une' },
            { name: 'Hypnotist\'s Watch', image: 'hypnotistsWatch', rarity: 'rare', frenchName: 'Montre d\'Hypnose' },
            { name: 'Vanishing Box', image: 'vanishingBox', rarity: 'rare', frenchName: 'Boîte de Disparition' },
            { name: 'Discarded Milk Carton', image: 'discardedMilkCarton', rarity: 'veryrare', frenchName: 'Brique de Lait Jetée' },
            { name: 'Homemade Mask', image: 'homemadeMask', rarity: 'veryrare', frenchName: 'Masque Fait Maison' },
            { name: 'Obscure Game Cartridge', image: 'obscureGameCartridge', rarity: 'veryrare', frenchName: 'Cartouche de Jeu Obscure' },
            { name: 'Serum Vial', image: 'serumVial', rarity: 'veryrare', frenchName: 'Fiole de Sérum' },
            { name: 'Captured by the Dark', image: 'capturedByTheDark', rarity: 'ultra', frenchName: 'Rapt par les Ténèbres' },
            { name: 'Iridescent OSS Report', image: 'iridescentOSSReport', rarity: 'ultra', frenchName: 'Rapport de l\'OSS Irisé' }
        ]
    }
};

const SURVIVOR_ITEMS = [
    { name: 'Chinese Firecracker', image: 'chineseFirecracker', type: 'firecracker', rarity: 'blank', frenchName: 'Pétard Chinois' },
    { name: 'Third Year Party Starter', image: 'thirdYearPartyStarter', type: 'firecracker', rarity: 'blank', frenchName: 'Cadeau de 3ème Anniversaire' },
    { name: 'Winter Party Starter', image: 'winterPartyStarter', type: 'firecracker', rarity: 'blank', frenchName: 'Papillote de la Fête d\'Hiver' },
    { name: 'Flashlight', image: 'flashlight', type: 'flashlight', rarity: 'uncommon', frenchName: 'Lampe de Poche' },
    { name: 'Sport Flashlight', image: 'sportFlashlight', type: 'flashlight', rarity: 'rare', frenchName: 'Lampe Torche de Sport' },
    { name: 'Utility Flashlight', image: 'utilityFlashlight', type: 'flashlight', rarity: 'veryrare', frenchName: 'Lampe de Poche Utilitaire' },
    { name: 'Anniversary Flashlight', image: 'anniversaryFlashlight', type: 'flashlight', rarity: 'blank', frenchName: 'Lampe de Poche d\'Anniversaire' },
    { name: 'Masquerade Flashlight', image: 'masqueradeFlashlight', type: 'flashlight', rarity: 'blank', frenchName: 'Lampe de Poche de Mascarade' },
    { name: 'Will O\' Wisp', image: 'willOWisp', type: 'flashlight', rarity: 'blank', frenchName: 'Feu Follet' },
    { name: 'Broken Key', image: 'brokenKey', type: 'key', rarity: 'rare', frenchName: 'Clé Cassée' },
    { name: 'Dull Key', image: 'dullKey', type: 'key', rarity: 'veryrare', frenchName: 'Clé Émoussée' },
    { name: 'Skeleton Key', image: 'skeletonKey', type: 'key', rarity: 'ultra', frenchName: 'Passe-Partout' },
    { name: 'Map', image: 'map', type: 'map', rarity: 'rare', frenchName: 'Carte' },
    { name: 'Rainbow Map', image: 'rainbowMap', type: 'map', rarity: 'ultra', frenchName: 'Carte Arc-en-ciel' },
    { name: 'Camping Aid Kit', image: 'campingAidKit', type: 'medkit', rarity: 'common', frenchName: 'Trousse de Soins de Camping' },
    { name: 'First Aid Kit', image: 'firstAidKit', type: 'medkit', rarity: 'uncommon', frenchName: 'Trousse de Premiers Soins' },
    { name: 'Emergency Med-Kit', image: 'emergencyMed-Kit', type: 'medkit', rarity: 'rare', frenchName: 'Trousse de Soins d\'Urgence' },
    { name: 'Ranger Med-Kit', image: 'rangerMed-Kit', type: 'medkit', rarity: 'veryrare', frenchName: 'Trousse de Soins de Garde Forestier' },
    { name: 'All Hallows\' Eve Lunchbox', image: 'allHallowsEveLunchbox', type: 'medkit', rarity: 'blank', frenchName: 'Boîte à Déjeuner d\'Halloween' },
    { name: 'Anniversary Med-Kit', image: 'anniversaryMed-Kit', type: 'medkit', rarity: 'blank', frenchName: 'Trousse de Soins d\'Anniversaire' },
    { name: 'Masquerade Med-Kit', image: 'masqueradeMed-Kit', type: 'medkit', rarity: 'blank', frenchName: 'Trousse de Soins de Mascarade' },
    { name: 'Worn-Out Tools', image: 'worn-OutTools', type: 'toolbox', rarity: 'common', frenchName: 'Outils Usés' },
    { name: 'Toolbox', image: 'toolbox', type: 'toolbox', rarity: 'uncommon', frenchName: 'Boîte à Outils' },
    { name: 'Commodious Toolbox', image: 'commodiousToolbox', type: 'toolbox', rarity: 'rare', frenchName: 'Boîte à Outils Spacieuse' },
    { name: 'Mechanic\'s Toolbox', image: 'mechanicsToolbox', type: 'toolbox', rarity: 'rare', frenchName: 'Boîte à Outils de Mécanicien' },
    { name: 'Alex\'s Toolbox', image: 'alexsToolbox', type: 'toolbox', rarity: 'veryrare', frenchName: 'Boîte à Outils d\'Alex' },
    { name: 'Engineer\'s Toolbox', image: 'engineersToolbox', type: 'toolbox', rarity: 'veryrare', frenchName: 'Boîte à Outils de Technicien' },
    { name: 'Anniversary Toolbox', image: 'anniversaryToolbox', type: 'toolbox', rarity: 'blank', frenchName: 'Boîte à Outils d\'Anniversaire' },
    { name: 'Festive Toolbox', image: 'festiveToolbox', type: 'toolbox', rarity: 'blank', frenchName: 'Boîte à Outils des Fêtes' },
    { name: 'Masquerade Toolbox', image: 'masqueradeToolbox', type: 'toolbox', rarity: 'blank', frenchName: 'Boîte à Outils de Mascarade' }
];

const ITEMS_ADDONS = {
    'flashlight': [
        { name: 'Battery', image: 'battery', rarity: 'common', frenchName: 'Pile' },
        { name: 'Leather Grip', image: 'leatherGrip', rarity: 'common', frenchName: 'Poignée en Cuir' },
        { name: 'Power Bulb', image: 'powerBulb', rarity: 'common', frenchName: 'Ampoule Électrique' },
        { name: 'Wide Lens', image: 'wideLens', rarity: 'common', frenchName: 'Lentille Large' },
        { name: 'Focus Lens', image: 'focusLens', rarity: 'uncommon', frenchName: 'Lentilles Focales' },
        { name: 'Heavy Duty Battery', image: 'heavyDutyBattery', rarity: 'uncommon', frenchName: 'Pile Haute Performance' },
        { name: 'Low Amp Filament', image: 'lowAmpFilament', rarity: 'uncommon', frenchName: 'Filament Bas Ampérage' },
        { name: 'Rubber Grip', image: 'rubberGrip', rarity: 'uncommon', frenchName: 'Poignée en Caoutchouc' },
        { name: 'TIR Optic', image: 'tirOptic', rarity: 'uncommon', frenchName: 'Optique à Réflexion Totale' },
        { name: 'Intense Halogen', image: 'intenseHalogen', rarity: 'rare', frenchName: 'Lampe Halogène Intense' },
        { name: 'Long Life Battery', image: 'longLifeBattery', rarity: 'rare', frenchName: 'Pile Longue Durée' },
        { name: 'High-End Sapphire Lens', image: 'highEndSapphireLens', rarity: 'veryrare', frenchName: 'Lentille Haut de Gamme en Saphir' },
        { name: 'Odd Bulb', image: 'oddBulb', rarity: 'ultra', frenchName: 'Ampoule Bizarre' }
    ],
    'key': [
        { name: 'Prayer Rope', image: 'prayerRope', rarity: 'common', frenchName: 'Corde de Prière' }
    ]
};
