const ROLES = [
    'killer',
    'survivor'
];

const SURVIVORS = [
    'dwight',
    'meg',
    'claudette',
    'jake',
    'nea',
    'laurie',
    'ace',
    'bill',
    'feng',
    'david',
    'quentin',
    'tapp',
    'kate',
    'adam',
    'jeff',
    'jane',
    'ash',
    'nancy',
    'steve',
    'yui',
    'zarina',
    'cheryl',
    'felix',
    'elodie',
    'yun',
    'jill',
    'leon',
    'mikaela',
    'jonah',
    'yoichi',
    'haddie',
    'ada',
    'rebecca',
    'vittorio',
    'thalita',
    'renato',
    'gabriel',
    'nicolas',
    'ellen',
    'alan',
    'sable'
]; // list of all available survivors

const KILLERS = [
    'trapper',
    'wraith',
    'hillbilly',
    'nurse',
    'shape',
    'hag',
    'doctor',
    'huntress',
    'cannibal',
    'nightmare',
    'pig',
    'clown',
    'spirit',
    'legion',
    'plage',
    'ghostface',
    'demogorgon',
    'oni',
    'deathslinger',
    'executioner',
    'blight',
    'twins',
    'trickster',
    'nemesis',
    'cenobite',
    'artist',
    'onryo',
    'dredge',
    'mastermind',
    'knight',
    'skullmerchant',
    'singularity',
    'xenomorph',
    'goodguy',
    'unknown'
]; // list of all available killers

const KILLER_PERKS = [
    'aNursesCalling',
    'agitation',
    'alienInstinct',
    'awakenedAwareness',
    'bamboozle',
    'barbecueAndChilli',
    'batteriesIncluded',
    'beastOfPrey',
    'bitterMurmur',
    'bloodEcho',
    'bloodWarden',
    'bloodhound',
    'brutalStrength',
    'callOfBrine',
    'corruptIntervention',
    'coulrophobia',
    'coupDeGr%3Fce',
    'cruelLimits',
    'darkDevotion',
    'darknessRevealed',
    'deadMansSwitch',
    'deadlock',
    'deathbound',
    'deerstalker',
    'discordance',
    'dissolution',
    'distressing',
    'dragonsGrip',
    'dyingLight',
    'enduring',
    'eruption',
    'fireUp',
    'forcedHesitation',
    'forcedPenance',
    'franklinsDemise',
    'friendsTilTheEnd',
    'furtiveChase',
    'gameAfoot',
    'gearhead',
    'geneticLimits',
    'grimEmbrace',
    'hexBloodFavour',
    'hexCrowdControl',
    'hexDevourHope',
    'hexFaceTheDarkness',
    'hexHauntedGround',
    'hexHuntressLullaby',
    'hexNoOneEscapesDeath',
    'hexPentimento',
    'hexPlaything',
    'hexRetribution',
    'hexRuin',
    'hexTheThirdSeal',
    'hexThrillOfTheHunt',
    'hexTwoCanPlay',
    'hexUndying',
    'hoarder',
    'hubris',
    'hysteria',
    'imAllEars',
    'infectiousFright',
    'insidious',
    'ironGrasp',
    'ironMaiden',
    'knockOut',
    'lethalPursuer',
    'leverage',
    'lightborn',
    'machineLearning',
    'madGrit',
    'makeYourChoice',
    'mercilessStorm',
    'mindbreaker',
    'monitorAndAbuse',
    'nemesis',
    'noWayOut',
    'nowhereToHide',
    'oppression',
    'overcharge',
    'overwhelmingPresence',
    'playWithYourFood',
    'popGoesTheWeasel',
    'predator',
    'rancor',
    'rapidBrutality',
    'rememberMe',
    'saveTheBestForLast',
    'scourgeHookFloodsOfRage',
    'scourgeHookGiftOfPain',
    'scourgeHookHangmansTrick',
    'scourgeHookMonstrousShrine',
    'scourgeHookPainResonance',
    'septicTouch',
    'shadowbord',
    'shatteredHope',
    'sloopyButcher',
    'spiesFromTheShadows',
    'spiritFury',
    'starstruck',
    'stridor',
    'superiorAnatomy',
    'surge',
    'surveillance',
    'terminus',
    'territorialImperative',
    'thanatophobia',
    'thrillingTremors',
    'thwack',
    'tinkerer',
    'trailOfTorment',
    'ultimateWeapon',
    'unbound',
    'undone',
    'unforeseen',
    'unnervingPresence',
    'unrelenting',
    'whispers',
    'zanshinTactics'
]; // list of all killers perks

const SURVIVOR_PERKS = [
    'aceInTheHole',
    'adrenaline',
    'aftercare',
    'alert',
    'anyMeansNecessary',
    'appraisal',
    'autodidact',
    'babysitter',
    'backgroundPlayer',
    'balancedLanding',
    'betterThanNew',
    'betterTogether',
    'biteTheBullet',
    'blastMine',
    'bloodPact',
    'bloodRush',
    'boilOver',
    'bond',
    'boonCircleOfHealing',
    'boonDarkTheory',
    'boonExponential',
    'boonIllumination',
    'boonShadowStep',
    'borrowedTime',
    'botanyKnowledge',
    'breakdown',
    'breakout',
    'buckleUp',
    'builtToLast',
    'calmSpirit',
    'camaraderie',
    'ChampionOfLight',
    'chemicalTrap',
    'clairvoyance',
    'correctiveAction',
    'counterforce',
    'cutLoose',
    'danceWithMe',
    'darkSense',
    'deadHard',
    'deadline',
    'deception',
    'decisiveStrike',
    'dejaVu',
    'deliverance',
    'desperateMeasures',
    'detectivesHunch',
    'distortion',
    'diversion',
    'dramaturgy',
    'empathicConnection',
    'empathy',
    'fastTrack',
    'fixated',
    'flashbang',
    'flip-Flop',
    'fogwise',
    'forThePeople',
    'friendlyCompetition',
    'headOn',
    'hope',
    'hyperfocus',
    'innerFocus',
    'innerStrength',
    'invocationWeavingSpiders',
    'ironWill',
    'kindred',
    'leader',
    'leftBehind',
    'light-Footed',
    'lightweight',
    'lithe',
    'lowProfile',
    'luckyBreak',
    'luckyStar',
    'madeForThis',
    'mettleOfMan',
    'noMither',
    'noOneLeftBehind',
    'objectOfObsession',
    'offTheRecord',
    'open-Handed',
    'overcome',
    'overzealous',
    'parentalGuidance',
    'pharmacy',
    'plotTwist',
    'plunderersInstinct',
    'poised',
    'potentialEnergy',
    'powerStruggle',
    'premonition',
    'proveThyself',
    'quickGambit',
    'reactiveHealing',
    'reassurance',
    'redHerring',
    'repressedAlliance',
    'residualManifest',
    'resilience',
    'resurgence',
    'rookieSpirit',
    'saboteur',
    'scavenger',
    'scenePartner',
    'secondWind',
    'self-Care',
    'self-Preservation',
    'slipperyMeat',
    'smallGame',
    'smashHit',
    'soleSurvivor',
    'solidarity',
    'soulGuard',
    'spineChill',
    'sprintBurst',
    'stakeOut',
    'streetwise',
    'strengthInShadows',
    'teamworkCollectiveStealth',
    'teamworkPowerOfTwo',
    'technician',
    'tenacity',
    'thisIsNotHappening',
    'troubleshooter',
    'unbreakable',
    'upTheAnte',
    'urbanEvasion',
    'vigil',
    'visionary',
    'wakeUp',
    'wellMakeIt',
    'wereGonnaLiveForever',
    'wicked',
    'windowsOfOpportunity',
    'wiretap'
]; // list of all survivor perks

const RARE_PERKS = [];

const KILLER_POWERS = {
    'trapper': {
        image: 'trap',
        addons: [
            { name: 'Bear Oil', image: 'bearOil', rarity: 'common', frenchName: 'Huile d\'ours' },
            { name: 'Makeshift Wrap', image: 'makeshiftWrap', rarity: 'common', frenchName: 'Écharpe Improvisée' },
            { name: 'Padded Jaws', image: 'paddedJaws', rarity: 'common', frenchName: 'Mâchoires Molletonnées' },
            { name: 'Trapper Gloves', image: 'trapperGloves', rarity: 'common', frenchName: 'Gants du Piégeur' },
            { name: '4-Coil Sprint Kit', image: '4-coilSpringKit', rarity: 'uncommon', frenchName: 'Kit à Quatre Ressorts' },
            { name: 'Coffee Grounds', image: 'coffeeGrounds', rarity: 'uncommon', frenchName: 'Café Moulu' },
            { name: 'Lengthened Jaws', image: 'lengthenedJaws', rarity: 'uncommon', frenchName: 'Mâchoires Allongées' },
            { name: 'Serrated Jaws', image: 'serratedJaws', rarity: 'uncommon', frenchName: 'Mâchoires Dentelées' },
            { name: 'Wax Brick', image: 'waxBrick', rarity: 'uncommon', frenchName: 'Brique de Cire' },
            { name: 'Fastening Tools', image: 'fasteningTools', rarity: 'rare', frenchName: 'Outils d\'Assemblage' },
            { name: 'Rusted Jaws', image: 'rustedJaws', rarity: 'rare', frenchName: 'Mâchoires Rouillées' },
            { name: 'Secondary Coil', image: 'secondaryCoil', rarity: 'rare', frenchName: 'Ressort Secondaire' },
            { name: 'Tar Bottle', image: 'tarBottle', rarity: 'rare', frenchName: 'Bouteille de Goudron' },
            { name: 'Trapper Bag', image: 'trapperBag', rarity: 'rare', frenchName: 'Sacoche du Piégeur' },
            { name: 'Honing Stone', image: 'honingStone', rarity: 'veryrare', frenchName: 'Pierre à Aiguiser' },
            { name: 'Oily Coil', image: 'oilyCoil', rarity: 'veryrare', frenchName: 'Ressort Huilé' },
            { name: 'Tension Spring', image: 'tensionSpring', rarity: 'veryrare', frenchName: 'Ressort à Tension' },
            { name: 'Trapper Sack', image: 'trapperSack', rarity: 'veryrare', frenchName: 'Sac du Piégeur' },
            { name: 'Bloody Coil', image: 'bloodyCoil', rarity: 'ultra', frenchName: 'Ressort Sanglant' },
            { name: 'Iridescent Stone', image: 'iridescentStone', rarity: 'ultra', frenchName: 'Pierre Irisée' }
        ]
    },
    'wraith': {
        image: 'bell',
        addons: [
            { name: '"The Beast" - Soot', image: 'theBeast-Soot', rarity: 'common', frenchName: '"La Bête" - Suie' },
            { name: '"The Ghost" - Soot', image: 'theGhost-Soot', rarity: 'common', frenchName: '"Ghost Face" - Suie' },
            { name: '"The Hound" - Soot', image: 'theHound-Soot', rarity: 'common', frenchName: '"Le Molosse" - Suie' },
            { name: '"The Serpent" - Soot', image: 'theSerpent-Soot', rarity: 'common', frenchName: '"Le Serpent" - Suie' },
            { name: '"Blind Warrior" - Mud', image: 'blindWarrior-Mud', rarity: 'uncommon', frenchName: '"Guerrier Aveugle" - Boue' },
            { name: '"Blink" - Mud', image: 'blink-Mud', rarity: 'uncommon', frenchName: '"Évanouissement" - Boue' },
            { name: '"Swift Hunt" - Mud', image: 'swiftHunt-Mud', rarity: 'uncommon', frenchName: '"Chasse Preste" - Boue' },
            { name: '"Windstorm" - Mud', image: 'windstorm-Mud', rarity: 'uncommon', frenchName: '"Tempête" - Boue' },
            { name: 'Bone Clapper', image: 'boneClapper', rarity: 'uncommon', frenchName: 'Battant en Os' },
            { name: '"Blind Warrior" - White', image: 'blindWarrior-White', rarity: 'rare', frenchName: '"Guerrier Aveugle" - Blanc' },
            { name: '"Blink" - White', image: 'blink-White', rarity: 'rare', frenchName: '"Évanouissement" - Blanc' },
            { name: '"Shadow Dance" - White', image: 'shadowDance-White', rarity: 'rare', frenchName: '"Danse de l\'Ombre" - Blanc' },
            { name: '"Swift Hunt" - White', image: 'swiftHunt-White', rarity: 'rare', frenchName: '"Chasse Preste" - Blanc' },
            { name: '"Windstorm" - White', image: 'windstorm-White', rarity: 'rare', frenchName: '"Tempête" - Blanc' },
            { name: '"All Seeing" - Blood', image: 'allSeeing-Blood', rarity: 'veryrare', frenchName: '"Clairvoyant" - Sang' },
            { name: '"Shadow Dance" - Blood', image: 'shadowDance-Blood', rarity: 'veryrare', frenchName: '"Danse de l\'Ombre" - Sang' },
            { name: '"Swift Hunt" - Blood', image: 'swiftHunt-Blood', rarity: 'veryrare', frenchName: '"Chasse Preste" - Sang' },
            { name: '"Windstorm" - Blood', image: 'windstorm-Blood', rarity: 'veryrare', frenchName: '"Tempête" - Sang' },
            { name: '"All Seeing" - Spirit', image: 'allSeeing-Spirit', rarity: 'ultra', frenchName: '"Clairvoyant" - Esprit' },
            { name: 'Coxcombed Clapper', image: 'coxcombedClapper', rarity: 'ultra', frenchName: 'Battant Encordé' }
        ]
    },
    'hillbilly': {
        image: 'chainsaw',
        addons: [
            { name: 'Counterweight', image: 'counterweight', rarity: 'common', frenchName: 'Contrepoids' },
            { name: 'Cracked Primer Bulb', image: 'crackedPrimerBulb', rarity: 'common', frenchName: 'Bulbe d\'Amorce Fissuré' },
            { name: 'Dad\'s Boots', image: 'dadsBoots', rarity: 'common', frenchName: 'Bottes de Papa' },
            { name: 'Steel Toe Boots', image: 'steelToeBoots', rarity: 'common', frenchName: 'Bottes à Embout d\'Acier' },
            { name: 'Clogged Intake', image: 'cloggedIntake', rarity: 'uncommon', frenchName: 'Entrée d\'Air Bouchée' },
            { name: 'Greased Throttle', image: 'greasedThrottle', rarity: 'uncommon', frenchName: 'Commande des Gaz Graissée' },
            { name: 'Off-Brand Motor Oil', image: 'off-BrandMotorOil', rarity: 'uncommon', frenchName: 'Huile Moteur Bon Marché' },
            { name: 'Spiked Boots', image: 'spikedBoots', rarity: 'uncommon', frenchName: 'Bottes à Pointes' },
            { name: 'Thermal Casing', image: 'thermalCasing', rarity: 'uncommon', frenchName: 'Revêtement Thermique' },
            { name: 'Begrimed Chains', image: 'begrimedChains', rarity: 'rare', frenchName: 'Chaînes Souillées' },
            { name: 'Low Kickback Chains', image: 'lowKickbackChains', rarity: 'rare', frenchName: 'Chaînes à Faible Recul' },
            { name: 'Ragged Engine', image: 'raggedEngine', rarity: 'rare', frenchName: 'Moteur Irrégulier' },
            { name: 'The Thompsons\' Mix', image: 'theThompsonsMix', rarity: 'rare', frenchName: 'Le Mélange des Thompson' },
            { name: 'Apex Muffler', image: 'apexMuffler', rarity: 'veryrare', frenchName: 'Silencieux de Pointe' },
            { name: 'Flithy Slippers', image: 'flithySlippers', rarity: 'veryrare', frenchName: 'Pantoufles Sales' },
            { name: 'High-Speed Idler Screw', image: 'high-SpeedIdlerScrew', rarity: 'veryrare', frenchName: 'Vis de Tendeur de Haut Régime' },
            { name: 'LoPro Chains', image: 'loProChains', rarity: 'veryrare', frenchName: 'Tronçonneuse Lo Pro' },
            { name: 'Iridescent Engravings', image: 'iridescentEngravings', rarity: 'ultra', frenchName: 'Gravures Irisées' },
            { name: 'Tuned Carburettor', image: 'tunedCarburettor', rarity: 'ultra', frenchName: 'Carburateur Réglé' }
        ]
    },
    'nurse': {
        image: 'breath',
        addons: [
            { name: 'Metal Spoon', image: 'metalSpoon', rarity: 'common', frenchName: 'Cuillère en Métal' },
            { name: 'Plaid Flannel', image: 'plaidFlannel', rarity: 'common', frenchName: 'Morceau de Plaid' },
            { name: 'White Nit Comb', image: 'whiteNitComb', rarity: 'common', frenchName: 'Peigne à Lentes Blanc' },
            { name: 'Wooden Horse', image: 'woodenHorse', rarity: 'common', frenchName: 'Cheval de Bois' },
            { name: 'Bad Man Keepsake', image: 'badManKeepsake', rarity: 'uncommon', frenchName: 'Souvenir du Méchant' },
            { name: 'Catatonic Boy\'s Treasure', image: 'catatonicBoysTreasure', rarity: 'uncommon', frenchName: 'Trésor d\'un Garçon Catatonique' },
            { name: 'Dark Cincture', image: 'darkCincture', rarity: 'uncommon', frenchName: 'Ceinture Obscure' },
            { name: 'Dull Bracelet', image: 'dullBracelet', rarity: 'uncommon', frenchName: 'Bracelet Terne' },
            { name: 'Pocket Watch', image: 'pocketWatch', rarity: 'uncommon', frenchName: 'Montre à Gousset' },
            { name: 'Anxious Gasp', image: 'anxiousGasp', rarity: 'rare', frenchName: 'Cri d\'Anxiété' },
            { name: 'Ataxic Respiration', image: 'ataxicRespiration', rarity: 'rare', frenchName: 'Respiration Ataxique' },
            { name: 'Fragile Wheeze', image: 'fragileWheeze', rarity: 'rare', frenchName: 'Respiration Difficile' },
            { name: 'Heavy Panting', image: 'heavyPanting', rarity: 'rare', frenchName: 'Halètement Intense' },
            { name: 'Spasmodic Breath', image: 'spasmodicBreath', rarity: 'rare', frenchName: 'Respiration Spasmodique' },
            { name: '"Bad Man\'s" Last Breath', image: 'badMansLastBreath', rarity: 'veryrare', frenchName: 'Dernier Souffle du "Méchant"' },
            { name: 'Campbell\'s Last Breath', image: 'campbellsLastBreath', rarity: 'veryrare', frenchName: 'Dernier Souffle de Campbell' },
            { name: 'Jenner\'s Last Breath', image: 'jennersLastBreath', rarity: 'veryrare', frenchName: 'Dernier Souffle de Jenner' },
            { name: 'Kavanagh\'s Last Breath', image: 'kavanaghsLastBreath', rarity: 'veryrare', frenchName: 'Dernier Souffle de Kavanagh' },
            { name: 'Matchbox', image: 'matchbox', rarity: 'ultra', frenchName: 'Boîte d\'Allumettes' },
            { name: 'Torn Bookmark', image: 'tornBookmark', rarity: 'ultra', frenchName: 'Signet Déchiré' }
        ]
    },
    'shape': {
        image: 'stalker1',
        addons: [
            { name: 'Blond Hair', image: 'blondHair', rarity: 'common', frenchName: 'Cheveux Blonds' },
            { name: 'Boyfriend\'s Memo', image: 'boyfriendsMemo', rarity: 'common', frenchName: 'Note du Petit Ami' },
            { name: 'Memorial Flower', image: 'memorialFlower', rarity: 'common', frenchName: 'Fleur Commémorative' },
            { name: 'Tacky Earrings', image: 'tackyEarrings', rarity: 'common', frenchName: 'Boucles d\'Oreilles Kitsch' },
            { name: 'Dead Rabbit', image: 'deadRabbit', rarity: 'uncommon', frenchName: 'Lapin Mort' },
            { name: 'Glass Fragment', image: 'glassFragment', rarity: 'uncommon', frenchName: 'Fragment de Verre' },
            { name: 'Hair Brush', image: 'hairBrush', rarity: 'uncommon', frenchName: 'Brosse à Cheveux' },
            { name: 'Jewellery', image: 'jewellery', rarity: 'uncommon', frenchName: 'Bijoux' },
            { name: 'Reflective Fragment', image: 'reflectiveFragment', rarity: 'uncommon', frenchName: 'Fragment Réfléchissant' },
            { name: 'Hair Bow', image: 'hairBow', rarity: 'rare', frenchName: 'Ruban' },
            { name: 'J. Myers Memorial', image: 'jMyersMemorial', rarity: 'rare', frenchName: 'Mémorial de J. Myers' },
            { name: 'Jewellery Box', image: 'jewelleryBox', rarity: 'rare', frenchName: 'Boite à Bijoux' },
            { name: 'Judith\'s Journal', image: 'judithsJournal', rarity: 'rare', frenchName: 'Journal de Judith' },
            { name: 'Mirror Shard', image: 'mirrorShard', rarity: 'rare', frenchName: 'Morceau de Miroir' },
            { name: 'Lock of Hair', image: 'lockOfHair', rarity: 'veryrare', frenchName: 'Mèche de Cheveux' },
            { name: 'Scratched Mirror', image: 'scratchedMirror', rarity: 'veryRare', frenchName: 'Miroir Rayé' },
            { name: 'Tombstone Piece', image: 'tombstonePiece', rarity: 'veryRare', frenchName: 'Morceau de Pierre Tombale' },
            { name: 'Vanity Mirror', image: 'vanityMirror', rarity: 'veryRare', frenchName: 'Miroir' },
            { name: 'Fragrant Tuft of Hair', image: 'fragrandTuftOfHair', rarity: 'ultra', frenchName: 'Touffe de Cheveux Parfumée' },
            { name: 'Judith\'s Tombstone', image: 'judithsTombstone', rarity: 'ultra', frenchName: 'Pierre Tombale de Judith' }
        ]
    },
    'hag': {
        image: 'blackenedCatalyst',
        addons: [
            { name: 'Bog Water', image: 'bogWater', rarity: 'common', frenchName: 'Eau du Bourbier' },
            { name: 'Dead Fly Mud', image: 'deadFlyMud', rarity: 'common', frenchName: 'Boue et Mouches Mortes' },
            { name: 'Powdered Eggshell', image: 'powderedEggshell', rarity: 'common', frenchName: 'Coquille d\'Oeuf Pulvérisée' },
            { name: 'Rope Necklet', image: 'ropeNecklet', rarity: 'common', frenchName: 'Collier en Corde' },
            { name: 'Bloodied Water', image: 'bloodiedWater', rarity: 'uncommon', frenchName: 'Eau Sanglante' },
            { name: 'Cypress Necklet', image: 'cypressNecklet', rarity: 'uncommon', frenchName: 'Collier en Cyprès' },
            { name: 'Dragonfly Wings', image: 'dragonflyWings', rarity: 'uncommon', frenchName: 'Ailes de Libellule' },
            { name: 'Half Eggshell', image: 'halfEggshell', rarity: 'uncommon', frenchName: 'Moitié de Coquille d\'Oeuf' },
            { name: 'Pussy Willow Catkins', image: 'pussyWillowCatkins', rarity: 'uncommon', frenchName: 'Chatons de Saulte' },
            { name: 'Bloodied Mud', image: 'bloodiedMud', rarity: 'rare', frenchName: 'Boue Sanglante' },
            { name: 'Cracked Turtle Egg', image: 'crackedTurtleEgg', rarity: 'rare', frenchName: 'Oeuf de Tortue Fêlé' },
            { name: 'Dried Cicada', image: 'driedCicada', rarity: 'rare', frenchName: 'Cigale Séchée' },
            { name: 'Swamp Orchid Necklet', image: 'swampOrchidNecklet', rarity: 'rare', frenchName: 'Collier d\'Orchidées des Marais' },
            { name: 'Willow Wreath', image: 'willowWreath', rarity: 'rare', frenchName: 'Couronne en Saule' },
            { name: 'Disfigured Ear', image: 'disfiguredEar', rarity: 'veryrare', frenchName: 'Oreille Déformée' },
            { name: 'Grandma\'s Heart', image: 'grandmasHeart', rarity: 'veryrare', frenchName: 'Coeur de Grand-Mère' },
            { name: 'Rusty Shackles', image: 'rustyshackles', rarity: 'veryrare', frenchName: 'Chaînes Rouillées' },
            { name: 'Scarred Hand', image: 'scarredHand', rarity: 'veryrare', frenchName: 'Main Balafrée' },
            { name: 'Mint Rag', image: 'mintRag', rarity: 'ultra', frenchName: 'Lambeau de Tissu Comme Neuf' },
            { name: 'Waterlogged Shoe', image: 'waterloggedShoe', rarity: 'ultra', frenchName: 'Chaussure Détrempée' }
        ]
    },
    'doctor': {
        image: 'cartersSpark',
        addons: [
            { name: '"Calm" - Class I', image: 'calm-ClassI', rarity: 'common', frenchName: '"Calme" - Cours I' },
            { name: '"Order" - Class I', image: 'order-ClassI', rarity: 'common', frenchName: '"Ordre" - Cours I' },
            { name: 'Maple Knight', image: 'mapleKnight', rarity: 'common', frenchName: 'Cavalier Érable' },
            { name: 'Mouldy Electrode', image: 'mouldyElectrode', rarity: 'common', frenchName: 'Vieille Électrode' },
            { name: '"Calm" - Class II', image: 'calm-ClassII', rarity: 'uncommon', frenchName: '"Calme" - Cours II' },
            { name: '"Discipline" - Class II', image: 'discipline-ClassII', rarity: 'uncommon', frenchName: '"Discipline" - Cours II' },
            { name: '"Order" - Class II', image: 'order-ClassII', rarity: 'uncommon', frenchName: '"Ordre" - Cours II' },
            { name: '"Restraint" - Class II', image: 'restraint-ClassII', rarity: 'uncommon', frenchName: '"Contrainte" - Cours II' },
            { name: 'Polished Electrode', image: 'polishedElectrode', rarity: 'uncommon', frenchName: 'Électrode Brillante' },
            { name: '"Discipline" - Class III', image: 'discipline-ClassIII', rarity: 'rare', frenchName: '"Discipline" - Cours III' },
            { name: '"Restraint" - Class III', image: 'restraint-ClassIII', rarity: 'rare', frenchName: '"Contrainte" - Cours III' },
            { name: 'High Stimulus Electrode', image: 'highStimulusElectrode', rarity: 'rare', frenchName: 'Électrode à Stimulation Élevée' },
            { name: 'Interview Tape', image: 'interviewTape', rarity: 'rare', frenchName: 'Cassette d\'Entretient'},
            { name: 'Scrapped Tape', image: 'scrappedTape', rarity: 'rare', frenchName: 'Cassette Abîmée' },
            { name: '"Calm" - Carter\'s Notes', image: 'calm-CartersNotes', rarity: 'veryrare', frenchName: '"Calme" - Notes de Carter' },
            { name: '"Discipline" - Carter\'s Notes', image: 'discipline-CartersNotes', rarity: 'veryrare', frenchName: '"Discipline" - Notes de Carter' },
            { name: '"Order" - Carter\'s Notes', image: 'order-CartersNotes', rarity: 'veryrare', frenchName: '"Ordre" - Notes de Carter' },
            { name: '"Restraint" - Carter\'s Notes', image: 'restraint-CartersNotes', rarity: 'veryrare', frenchName: '"Contrainte" - Notes de Carter' },
            { name: 'Iridescent King', image: 'iridescentKing', rarity: 'ultra', frenchName: 'Roi Irisé' },
            { name: 'Iridescent Queen', image: 'iridescentQueen', rarity: 'ultra', frenchName: 'Reine Irisée' }
        ]
    },
    'huntress': {
        image: 'huntingHatchets',
        addons: [
            { name: 'Amanita Toxin', image: 'amanitaToxin', rarity: 'common', frenchName: 'Toxine d\'Amanite' },
            { name: 'Bandaged Haft', image: 'bandagedHaft', rarity: 'common', frenchName: 'Manche Bandé' },
            { name: 'Coarse Stone', image: 'coarseStone', rarity: 'common', frenchName: 'Pierre Grossière' },
            { name: 'Yellowed Cloth', image: 'yellowedCloth', rarity: 'common', frenchName: 'Tissu Jaune' },
            { name: 'Leather Loop', image: 'leatherLoop', rarity: 'uncommon', frenchName: 'Boucle en Cuir' },
            { name: 'Manna Grass Braid', image: 'mannaGrassBraid', rarity: 'uncommon', frenchName: 'Tresse de Glycérie' },
            { name: 'Oak Haft', image: 'oakHaft', rarity: 'uncommon', frenchName: 'Manche en Chêne' },
            { name: 'Shiny Pin', image: 'shinyPin', rarity: 'uncommon', frenchName: 'Épingle Brillante' },
            { name: 'Weighted Head', image: 'weightedHead', rarity: 'uncommon', frenchName: 'Tête Lestée' },
            { name: 'Deerskin Gloves', image: 'deerskinGloves', rarity: 'rare', frenchName: 'Gants en Peau de Daim' },
            { name: 'Flower Babushka', image: 'flowerBabushka', rarity: 'rare', frenchName: 'Poupée Russe à Fleurs' },
            { name: 'Rose Root', image: 'roseRoot', rarity: 'rare', frenchName: 'Racine de Rose' },
            { name: 'Rusty Head', image: 'rustyHead', rarity: 'rare', frenchName: 'Tête Rouillée' },
            { name: 'Venomous Concoction', image: 'venomousConcoction', rarity: 'rare', frenchName: 'Concoction Vénéneuse' },
            { name: 'Begrimed Head', image: 'begrimedHead', rarity: 'veryrare', frenchName: 'Tête Souillée' },
            { name: 'Glowing Concoction', image: 'glowingConcoction', rarity: 'veryrare', frenchName: 'Concoction Luisante' },
            { name: 'Infantry Belt', image: 'infantryBelt', rarity: 'veryrare', frenchName: 'Ceinture d\'Infanterie' },
            { name: 'Wooden Fox', image: 'woodenFox', rarity: 'veryrare', frenchName: 'Renard de Bois' },
            { name: 'Iridescent Head', image: 'iridescentHead', rarity: 'ultra', frenchName: 'Tête Irisée' },
            { name: 'Soldier\'s Puttee', image: 'soldiersPuttee', rarity: 'ultra', frenchName: 'Bande Molletière de Soldat' }
        ]
    },
    'cannibal': {
        image: 'bubbasChainsaw',
        addons: [
            { name: 'Chainsaw File', image: 'chainsawFile', rarity: 'common', frenchName: 'Aiguiseur de Chaîne' },
            { name: 'Spark Plug', image: 'sparkPlug', rarity: 'common', frenchName: 'Bougie d\'Allumage' },
            { name: 'Speed Limiter', image: 'speedLimiter'}
        ]
    }
}
